### ISSUE TITLE
Remapping s key?

### ISSUE THREAD

**Issue by davidvalaz** [ggandor/lightspeed.nvim#10]
I'd like to remap <kbd>s</kbd> to another key. I see in the docs you have:
```
`<Plug>Lightspeed_s`
```

But for those of us not using `vim-plug` how does one accomplish a remap?

**Comment by ggandor** [comment]
`<Plug>` keys are a feature of Vim itself, they are just aliases for right hand sides of mappings. See [this issue](https://github.com/ggandor/lightspeed.nvim/issues/11), I answered in more detail there.

**Comment by ggandor** [comment]
I might update the help file, not assuming there that everyone is familiar with using `<Plug>` mappings. Thanks for bringing this up!

**Comment by davidvalaz** [comment]
Brilliant thanks so much. The `noremap` reference was key too. This sure does live up to its name.

Also, may be worth putting in a reference to `packer.nvim` like:
```
use 'ggandor/lightspeed.nvim'
```
Most of us that have dived head first into Neovim + Lua use it so gives a good initial first impression.

**Comment by ggandor** [comment]
Glad to hear everything works out well. Will add the `packer` section.
