### ISSUE TITLE
Lightspeed sometimes can't seem to jump to a word that it should

### ISSUE THREAD

**Issue by macintacos** [ggandor/lightspeed.nvim#103]
I've noticed weird behavior that I can only really explain with pictures/a demo. I have the following buffer, and I want to jump to the `ln` on the last line:

![CleanShot iTerm2 2021-12-05 at 22 06 51](https://user-images.githubusercontent.com/8128941/144780821-890bb8f6-498a-4678-99ab-6104af98183a.png)

I remap `s` to `f`, so keep that in mind when I explain the behavior below.

From where the cursor is positioned, I hit `f` and then type `ln` and _sometimes_ it doesn't jump to that position, or at least narrow down the results. There doesn't seem to be a ton of rhyme or reason to it, but sometimes I can't jump to it, but if I scroll around a little bit, I can. I can't figure out what the pattern is.

Here's the demo:

https://user-images.githubusercontent.com/8128941/144781315-43a1ee12-696a-4ba7-befb-f86d8a04aceb.mp4

Any idea what I could be doing wrong?

**Comment by ggandor** [comment]
This is most probably the same issue as #98. If you  start the search from a line that is indented with a `tab`, lightspeed calculates the editable area of the window incorrectly. Can you confirm?

**Comment by macintacos** [comment]
Will try again soon and let you know!

**Comment by macintacos** [comment]
Yep, it looks like I can't reproduce this anymore, yay! Thanks for the fantastic plugin :)
