### ISSUE TITLE
f/t inherits ignorecase/smartcase while s doesn't

### ISSUE THREAD

**Issue by novadev94** [ggandor/lightspeed.nvim#104]
This is really confusing - switching from "vanilla" Vim as the default f/t doesn't inherits ignorecase/smartcase - they're always case-sensitive.

For example
```
abcXyzx
_
```
(cursor is at `_`)

`fx` in default Vim jumps to the last character while lightspeed's `fx` jumps to the `X` character. And even more confusing, lightspeed's `sx` jumps to the last character...

I think f/t case sensitivity behavior should be configurable or be made case-sensitive.

Thanks for the great plugin!

**Comment by ggandor** [comment]
You have a point here, it would be better to make f/t and s/x consistent, even if that means forcing case-sensitivity for f/t. (The whole smartcase/ignorecase issue regarding s/x has been discussed back and forth in #64. Case-insensitivity as an option is not entirely out of the question, but even that is not a simple task for s/x.)

**Comment by novadev94** [comment]
Making f/t case sensitive would be great because it will be consistent with what s/x and Vim default f/t are doing.
