### ISSUE TITLE
Inconsistent handling of ;/,

### ISSUE THREAD

**Issue by levouh** [ggandor/lightspeed.nvim#105]
When searching forwards with `f`, I can seemingly repeat `;` as many times as I want and it will search across multiple lines just as expected. However, when using `,` (which I have remapped to `\`, however the functionality is the same no matter what I map it to) it does not seem to work. See the sample below:

https://user-images.githubusercontent.com/31262046/145144448-be087e52-e119-4b15-923d-3fa96e919e16.mp4

Where I would expect `\` (or `,` by default) to act just like `;` and keep searching backwards, but sometimes it just doesn't work. A "fresh" search backwards with `F` works just as expected (when searching "forwards" with `;`), but again, breaks when going "backwards" with `\`. It seems a bit more consistent if we surpass the timeout for the action, such that the `\` action is treated as a "fresh" action? Not sure if that makes sense, but it is shown in the above sample.

My configuration is nothing special:

```lua
  require("lightspeed").setup({})

  vim.api.nvim_set_keymap("n", "x", "<Plug>Lightspeed_s", { silent = true })
  vim.api.nvim_set_keymap("n", "X", "<Plug>Lightspeed_S", { silent = true })
  vim.api.nvim_set_keymap("v", "x", "<Plug>Lightspeed_s", { silent = true })
  vim.api.nvim_set_keymap("v", "X", "<Plug>Lightspeed_S", { silent = true })
  vim.api.nvim_set_keymap("n", [[\]], "<Plug>Lightspeed_,_ft", { silent = true })
  vim.api.nvim_set_keymap("v", [[\]], "<Plug>Lightspeed_,_ft", { silent = true })
  vim.api.nvim_set_keymap("o", [[\]], "<Plug>Lightspeed_,_ft", { silent = true })
```

**Comment by ggandor** [comment]
This is totally intentional. From the [README](https://github.com/ggandor/lightspeed.nvim#repeating-motions):

>  S, F and T, on the other hand, always revert the previous repeat. Note that in the case of T (or X, if mapped), this results in a different, and presumably more useful behaviour than what you are used to in clever-f and Sneak: it does not repeat the search in the reverse direction, but puts the cursor back to its previous position - before the previous match -, allowing for an easy correction when you accidentally overshoot your target.

And `;`/`,` work the same way. So the opposite key basically just crawls back on the stack of matches so far. This might feel odd for the very first time, after vanilla Vim, but our method is in fact a hundred times more logical (and useful). In real life, one would never want to start searching in the opposite direction, _before_ doing anything else in the target position.

**Comment by levouh** [comment]
Gotcha. I will probably have to just extend the timeout a bit as my brain isn't quite working at _lightspeed_ yet.
