### ISSUE TITLE
excessive highlights

### ISSUE THREAD

**Issue by fastbodin** [ggandor/lightspeed.nvim#106]
Thanks so much for you work on the plugin. After a recent change to the plugin, I appear to be having troubles with run-away highlighting. I have tested just using lightspeed with the default configurations. Below is the sequence of highlights that happen after I type 

S
 
then 

g

Perhaps this is something I am doing wrong, but like I said, it is the only plugin running in this test. I put this up here in case it was a common issue that other people were having, if it is not common I will update with minimal config.

By the way, I love the new unique character option. It is fantastic.

![Screen Shot 2021-12-08 at 10 31 01 AM](https://user-images.githubusercontent.com/35845723/145264252-1f9a30f1-8647-4bb8-bbc2-92c18ebd5146.png)
![Screen Shot 2021-12-08 at 10 31 30 AM](https://user-images.githubusercontent.com/35845723/145264266-0e6dfd49-0c28-483f-9b56-0e142ad03211.png)
![Screen Shot 2021-12-08 at 10 31 15 AM](https://user-images.githubusercontent.com/35845723/145264274-f9fd2e46-322a-441e-91dc-2cc3c0476981.png)

**Comment by ggandor** [comment]
Interesting. Have you tried with `nvim -u NONE`, and manually sourcing `lightspeed.lua` (just navigate to the directory of the plugin, and `luafile %`)? Or first, just try it without calling `setup` at all (it's not necessary in fact).

**Comment by fastbodin** [comment]
Good thought. I just tested without lightspeed.setup(). The problem went away. I isolated commands in the default configuration given on the main page:

require'lightspeed'.setup {
  exit_after_idle_msecs = { labeled = nil, unlabeled = 1000 },

  -- s/x
  grey_out_search_area = true,
  highlight_unique_chars = true,
  match_only_the_start_of_same_char_seqs = true,
  jump_on_partial_input_safety_timeout = 400,
  substitute_chars = { ['\r'] = '¬' },
  -- Leaving the appropriate list empty effectively disables
  -- "smart" mode, and forces auto-jump to be on or off.
 safe_labels = { ... },
  labels = { ... },
  cycle_group_fwd_key = '<space>',
  cycle_group_bwd_key = '<tab>',

  -- f/t
  limit_ft_matches = 4,
  repeat_ft_with_target_char = false,
}

The command that causes the problem is

safe_labels = { ... },

presumably I should have just commented that and labels out since I am not giving any inputs?

**Comment by ggandor** [comment]
Oh, sure, `{ ... }` is just illustration, of course you should either give proper lists of characters, or not touch them :)

> presumably I should have just commented that and labels out since I am not giving any inputs?

Yeah, generally it is not too good an idea to copy the defaults into your config if you're not overwriting anything, because any change in the interface might cause you unnecessary troubles then when updating.

**Comment by fastbodin** [comment]
Yes, for sure, these are sage words. In my own defence, I changed them originally then, when it was giving a weird behaviour, I reverted to the default to try and figure out if it was my problem :P

Thanks so helping me out so quickly and the work on the plugin!
