### ISSUE TITLE
mimic vim-sneak repeat f/F behaviour

### ISSUE THREAD

**Issue by sunjon** [ggandor/lightspeed.nvim#107]
I'm a fan of the sneak behaviour whereby if you've started an `f`/forward movement, selecting `F` automatically highlights all preceeding matches, as if the search had begun from the current cursor position.

Is this possible to reproduce with lightspeed?

**Comment by ggandor** [comment]
> ...highlights all preceeding matches, as if the search had begun from the current cursor position.

Not "as if" - if you press `F` while doing `f`, Sneak actually starts a new search in the reverse direction. And I ask: why would anyone want to do this (in practice)? At first, Lightspeed behaved exactly like Sneak, but it's been changed intentionally. Related: #105

**Comment by sunjon** [comment]
I find it quite intuitive.
The first search might _not_ be my move target. I initiate it for the visual highlight.
The direction I go is most often the one that sneak/lightspeed initiated in, but occasionally it's reverse.

**Comment by ggandor** [comment]
> The first search might not be my move target. I initiate it for the visual highlight.

I don't understand this at all. `f` only highlights matches in the forward direction, and `F` in the backward direction, so what good do they do if you aim for a target in the opposite direction?

**Comment by sunjon** [comment]
If sneak is active:

cursor position and highlighting indicate state and direction. "yes" sneak is active, and "yes, you're going this direction".

If lightspeed is active and you do an "f -> F" sequence, there's no highlighting at all.
No state, no direction.

**Comment by ggandor** [comment]
Sorry, but this still makes zero sense to me. You mean you use Sneak `f/F` to actually _search_ in the window, when you don't know where your target is, and you just start it in an arbitrary direction, hoping that you guessed right, and turning around, if not?

**Comment by sunjon** [comment]
I'm not sure what there's not to get :]

It's the same way that incsearch works - albeit highlighting only targets in the current search direction. There's no "this is where you started search mode" until you exit.

You're in a mode, and you can toggle direction. It's as simple as that.
I chose this plugin specifically for the sneak behaviour, if you're not interested in going in that direction, it's fine.

**Comment by ggandor** [comment]
> You're in a mode, and you can toggle direction. It's as simple as that.

I totally get it. What I do not get is the _point_ of switching directions after starting an `f` motion. :) 

1. If you are searching for a pattern, not knowing if there is a target at all, then use `/?` (possibly with incsearch enabled), that's what they are for - it's much-much-much faster to type 3-5 chars and using `ctrl-g/t` (or `n/N`), than initiating a 1-char search (`f`), possibly turning around, and then skipping through an awful lot of false positives. 

2. Otherwise, if you see the target, and know where you want to jump, then why on Earth would you want to turn around in the middle of the motion? What's the point of highlighting the targets in the opposite direction?

**Comment by sunjon** [comment]
I find it useful as a visual aid. I may not reverse direction, but hit <reverse search>  to see the preceeding matches. It's contextual and definitely a useful addition to my workflow.

For the record, I do find the language "why on earth", "this makes zero sense to me" language unnecessary. I feel it was a design choice from a very popular plugin that I happened to like. As I said, if you don't want to go in that direction, it's fine.

**Comment by ggandor** [comment]
> For the record, I do find the language "why on earth", "this makes zero sense to me" language unnecessary. 

Yeah, sorry for that, I should have kept in mind that such intense wording in writing without metacommunication might not be read as casual or playful as intended, just tried to express my utter confusion.

> to see the preceeding matches

You're talking about all the matches in the window, or the matches skipped so far? 

Anyway, it's still hard to imagine any situation where I would be interested in the preceding positions of the given `char`, when all I'm doing ultimately is moving/selecting from A to B - `char` is just a means to achieve that. I'd be really glad if you could come up with an illustrative example.
