### ISSUE TITLE
Wrong jump on second layer with label `s`

### ISSUE THREAD

**Issue by kuntau** [ggandor/lightspeed.nvim#108]
Hi. I'm including a screencast to better illustrate the problem.

Here's what I'm doing step by step.

1. My cursor at the start of the file `0,0`
2. In this example I'm targeting line **58** `Plug('hrsh7th/cmp-copilot')`
3. Press `s` followed by `'`
4. Press `)`
5. At this point we can see there is _red_ `s` on the first line and _blue_ `s` on line 58
6. Press `<space>` to enable the second part
7. _Blue_ label turned to _red_
8. Press `s`
9. Lightspeed jump to `'` on the first line without label _(previously was `s`)_ instead of line **58**
10. If I press other label `f` & `n` on as on the screencast. Lightspeed jump correctly to the line

[![asciicast](https://asciinema.org/a/iv5BnjAyVjTxBh9mrkrfhshbe.png)](https://asciinema.org/a/iv5BnjAyVjTxBh9mrkrfhshbe)

Thank you

**Comment by ggandor** [comment]
Good catch, thank you!
