### ISSUE TITLE
`let g:loaded_lightspeed = 1`

### ISSUE THREAD

**Issue by HaleTom** [ggandor/lightspeed.nvim#114]
If you type:

`:echom loaded_`

and hit <kbd>TAB</kbd>

you'll see that well behaved plugins set this flag.

Can you set it too?

**Comment by HaleTom** [comment]
Thank you :)

**Comment by ggandor** [comment]
Note that for Lua plugins this is a bit redundant, as you can simply check `package.loaded.lightspeed`.
