### ISSUE TITLE
Bug?: labels are disabled in the example configuration

### ISSUE THREAD

**Issue by shofel** [ggandor/lightspeed.nvim#115]
Hello!

I happily migrated from sneak to lightspeed. Thanks for the plugin! And I'd like to tell you a cool story about a pitfall I encountered while trying to make labels working :)

## Part 1. Example Configuration Have Labels Disabled
I copy-pasted the [example configuration](https://github.com/ggandor/lightspeed.nvim#-configuration)  from the readme, and found my self without labels. Have had quite hard time searching for the reason: tried downgrade vim, and tried to remove other plugins, and tried to bisect my init.vim to find the line which breaks the labels of lightspeed :D

Then it appeared the reason is the very example configuration from readme. Without it labels work properly.

## Part 2. It's Hard to Set Default Labels after Disabling Them
1. remove call of `require'lightspeed'.setup` from nvim init file
2. restart neovim
3. execute `:lua require'lightspeed'.setup {}`
4. --> (OK) got default labels
5. execute `:lua require'lightspeed'.setup { safe_labels = nil, labels = nil }`
6. --> (OK) labels are still default
5. execute `:lua require'lightspeed'.setup { safe_labels = {}, labels = {} }`
6. --> (OK) labels are disabled
7. execute `:lua require'lightspeed'.setup {}
8. --> (FAIL) expect labels to be default, but they are disabled

## Briefly
So, I believe, we've got two issues here:
1. example configuration (by accident?) uses table made of multiargs `{...}` for `labels` and `safe-labels`, effectively setting both to empty tables
2. `labels` and `safe_labels` are not falling back to defaults after being once set to an empty table

## P.S.
I think I can make an MR, when we settle on what to be done here

**Comment by ggandor** [comment]
Hi! The config snippet is meant to be an illustration, that is literally just an ellipsis in `{ ... }` - I forgot that it is actually valid Lua code, sorry for that :) I also noted above the snippet that it's not necessary to call `setup`, and even less to copy/paste the defaults into the config. I'll try to make that more obvious next time I'll do some tweaks to the README (and also change `...` to something else, e.g. `{<list of labels>}`).

**Comment by ggandor** [comment]
> execute :lua require'lightspeed'.setup { safe_labels = {}, labels = {} }
--> (OK) labels are disabled
execute `:lua require'lightspeed'.setup {}
--> (FAIL) expect labels to be default, but they are disabled

`setup` just updates the settings that appear in its argument table. It does not reset the defaults every time it's called. `setup {}` does nothing. See `:h lightspeed-config`.
