### ISSUE TITLE
How do I disable the update message every time I open nvim?

### ISSUE THREAD

**Issue by kohane27** [ggandor/lightspeed.nvim#117]
Whenever I launch nvim, the following appears on a new buffer:

```
ligthspeed.nvim
The following fields in the opts table has been renamed or removed:

        highlight_unique_chars
        jump_on_partial_input_safety_timeout
        grey_out_search_area

highlight_unique_chars
Use jump_to_unique_chars instead. See :h lightspeed-config for details.

jump_on_partial_input_safety_timeout
Use jump_to_unique_chars instead. See :h lightspeed-config for details.

grey_out_search_area
This flag has been removed. To turn the 'greywash' feature off, just set all attributes of the correspo
nding highlight group to 'none': :hi LightspeedGreywash guifg=none guibg=none ...
```

How do I disable this update message every time I open nvim? Thank you.

**Comment by ggandor** [comment]
First: note that you _don't have to copy/paste the defaults_ - I suspect you have a config copied from (some earlier version of) the README. You only need to call `setup` if you would like to customize things. 
If that's not the case, then, well, just follow the instructions in the message, and update your `setup` call accordingly, changing or removing the listed options.
If something is not clear, just say so, and I'll help you further.

**Comment by kohane27** [comment]
Hello ggandor. Thank you for getting back to me on such short notice. I appreciate it.

After disabling the following old config, the message is gone:

```
lightspeed.setup {
  exit_after_idle_msecs = { labeled = nil, unlabeled = 10000 },
  -- s/x
  grey_out_search_area = true,
  highlight_unique_chars = true,
  match_only_the_start_of_same_char_seqs = true,
  jump_on_partial_input_safety_timeout = 10000,
  -- f/t
  limit_ft_matches = 8,
  repeat_ft_with_target_char = false,
}

```'

Thanks again!
