### ISSUE TITLE
Search area is not grayed out on neovim nightly

### ISSUE THREAD

**Issue by Gelio** [ggandor/lightspeed.nvim#121]
Hey! I've been a huge fan of this plugin and it makes me so much productive

I've noticed that after my recent upgrade to Neovim nightly, I don't get the search area to be highlighted in grey after I press `s`

![image](https://user-images.githubusercontent.com/889383/149957844-f83d1811-d979-41cb-b292-762592ff870b.png)

Notice that I get the "1-press beacons" highlighted in white, but the text is not greyed out like it was previously.

I have compiled neovim from source using the latest neovim master, which at the time of writing is [`fcf5dd34fdfde3a6632b96a88f66c1053cba08d1`](https://github.com/neovim/neovim/tree/fcf5dd34fdfde3a6632b96a88f66c1053cba08d1)

```sh
$ nvim -v
NVIM v0.7.0-dev+905-gfcf5dd34f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/ubuntu/.local/neovim/build/config -I/home/ubuntu/.local/neovim/src -I/home/ubuntu/.local/neovim/.deps/usr/include -I/usr/include -I/home/ubuntu/.local/neovim/build/src/nvim/auto -I/home/ubuntu/.local/neovim/build/include
Compiled by ubuntu@grzegorz-dev-0-dev
```

I can't tell when this happened precisely and which range of commits might have caused that. I don't think I changed anything in my colorscheme's or lightspeed's configuration that caused this to break.

I tried running `:lua require'lightspeed'.init_highlight(true)` but that didn't help.

Interestingly, I've noticed there one piece of text that is correctly grayed out, and it's output redirects in bash files:

Normal: 
![image](https://user-images.githubusercontent.com/889383/149958561-8f05505b-ea71-4014-b657-04563bb62451.png)

After pressing `s`
![image](https://user-images.githubusercontent.com/889383/149958515-7fc9131d-3ebf-4b4a-a7fd-3764a14c394f.png)

After pressing `a`:

![image](https://user-images.githubusercontent.com/889383/149958906-af40720b-8f16-493d-b17d-a2839934ad9f.png)

**Comment by ggandor** [comment]
Should be fixed by the above PR, but let me know if the issue still persists!

**Comment by Gelio** [comment]
Thanks for a quick fix!

This indeed helps with the majority of highlights
![image](https://user-images.githubusercontent.com/889383/149998567-685b9920-f772-47d1-8365-83c261b287ea.png)

The only highlights that remain in their normal color are the highlights from https://github.com/folke/todo-comments.nvim. I don't mind them keeping the usual highlight, but having them also greyed out would be ideal.

If I'm not mistaken, this is the code that does the highlighting in `todo-comments.nvim`: https://github.com/folke/todo-comments.nvim/blob/672cd22bd15928434374ac52d0cf38dd250231df/lua/todo-comments/highlight.lua#L80. I didn't see any way to configure the highlighting priority in that plugin
