### ISSUE TITLE
Exception thrown when character was not found for bidirectional (omni) search

### ISSUE THREAD

**Issue by EtiamNullam** [ggandor/lightspeed.nvim#125]
I just noticed there is an option now for bidirectional search despite the old request issue (#8) is still marked as `wontfix`.

When using bidirectional search `<Plug>Lightspeed_omni_s` exception is thrown when character is not found instead of just a message in statusline like it is for the other commands (for example `not found: x`).

```
E5108: Error executing lua ~\.vim-plug\lightspeed.nvim/lua/lightspeed.lua:1346: attempt to get length of local 'targets' (a nil value)
stack traceback:
  ~\.vim-plug\lightspeed.nvim/lua/lightspeed.lua:1346: in function 'get_targets'
  ~\.vim-plug\lightspeed.nvim/lua/lightspeed.lua:2161: in function 'go'
```

NOTE: I shortened paths above to remove my username.

PS: Is bidirectional search planned for search between windows? Something like `<Plug>Lightspeed_omni_gs`?

**Comment by ggandor** [comment]
Fixed, thanks!

> PS: Is bidirectional search planned for search between windows? Something like <Plug>Lightspeed_omni_gs?

Yes, probably.
