### ISSUE TITLE
Setup invalid in most recent commit

### ISSUE THREAD

**Issue by jacksonludwig** [ggandor/lightspeed.nvim#127]
Thought I would inform that I believe you accidentally deleted the `lua/lightspeed.lua` file in your latest commit.

**Comment by zbirenbaum** [comment]
While we wait on a fix, you can use my fork which adds it back. Just change the link in packer.
https://github.com/zbirenbaum/lightspeed.nvim

**Comment by rod-stuchi** [comment]
targeting to a commit before the "bug" in Packer works as well.

```lua
  use {
    'ggandor/lightspeed.nvim',
    commit = '4d8359a30b26ee5316d0e7c79af08b10cb17a57b'
  }
```

**Comment by zbirenbaum** [comment]
> targeting to a commit before the "bug" in Packer works as well.
> 
> ```lua
>   use {
>     'ggandor/lightspeed.nvim',
>     commit = '4d8359a30b26ee5316d0e7c79af08b10cb17a57b'
>   }
> ```
This is true, but since the latest change claims to have fixed a breaking change from neovim, I thought it would be better to have a version which addresses that issue as well in case it is relevant for anyone.

**Comment by ggandor** [comment]
Epic fail. We need CI :)

**Comment by ggandor** [comment]
I guess @p00f went a bit too far in improving the startup time...
