### ISSUE TITLE
`s` command throws when `ignore_case = true`

### ISSUE THREAD

**Issue by scheatkode** [ggandor/lightspeed.nvim#136]
Hi,

First off, thank you for this amazing plugin !

c4a203de0a9696955a2468a88bc1ce2a5934357d seems to have broken the `s` command when `ignore_case` is enabled, with the following error on Neovim stable :

```
E5108: Error executing lua .../site/pack/packer/opt/lightspeed.nvim/lua/lightspeed.lua:1220: attempt to index local 'ch' (a nil value)
stack traceback:
        .../site/pack/packer/opt/lightspeed.nvim/lua/lightspeed.lua:1220: in function 'get_unique_chars'
        .../site/pack/packer/opt/lightspeed.nvim/lua/lightspeed.lua:2149: in function 'go'
        [string ":lua"]:1: in main chunk
```

This happens with `z`and `gs` as well.

Pretty sure this has nothing to do with #131 considering the time-frame. Apologies for not being able to open a PR, my only experience with fennel is a distant memory of being clumsy with Lisp.

Thank you for your time and efforts !

**Comment by ggandor** [comment]
Fixed, thanks very much!
