### ISSUE TITLE
Error executing lua vim.lua:0: attempt to call method 'byte' (a nil value)

### ISSUE THREAD

**Issue by lars-vc** [ggandor/lightspeed.nvim#139]
![image](https://user-images.githubusercontent.com/57136208/158022573-a293f2f2-2f83-4e08-b675-64b60395aac1.png)
I get this error when I press s, I don't really know since when lightspeed broke for me (I have been able to use it in the past). I recently did a :PlugUpdate so maybe an update broke something?

**Comment by lars-vc** [comment]
Ah my bad I see this issue is being covered in a different issue #131, I will attempt those suggested fixes and report back on that issue

**Comment by ggandor** [comment]
Duplicate of #131
