### ISSUE TITLE
Update configuration in init.vim

### ISSUE THREAD

**Issue by Muzzamil1** [ggandor/lightspeed.nvim#148]
Hi @ggandor thanks for this amazing plugin. 

I wanted to use case-insensitive. I am using init.vim instead of lua. Can you please tell me how to set `ignore_case = true ` in init.vim?

**Comment by ggandor** [comment]
```vim
lua require('lightspeed').opts.ignore_case = true
```
or, if you want to set multiple options, the simplest thing to do is:
```
lua << EOF
  -- you can write any Lua code here, just as you would in init.lua  
  require('lightspeed').setup {
    ignore_case = true,
    etc...    
  }
EOF
```

See e.g.: https://github.com/nanotee/nvim-lua-guide#using-lua-from-vimscript

**Comment by Muzzamil1** [comment]
Hi, thanks for your response. I am using [vscode-neovim](https://github.com/vscode-neovim/vscode-neovim)

I am actually using init.vim for configuration, not init.lua. I tried the configuration that you send but that gives error 

```
E5108: Error executing lua [string ":lua"]:1: module 'lightspeed' not found:
	no field package.preload['lightspeed']
	no file '.\lightspeed.lua'
	no file 'C:\Neovim\bin\lua\lightspeed.lua'
	no file 'C:\Neovim\bin\lua\lightspeed\init.lua'
	no file '.\lightspeed.dll'
	no file 'C:\Neovim\bin\lightspeed.dll'
	
````

I also tried some settings that I know of but nothing worked (please check the green box in the screenshot). Sorry I don't have experience with lua. I really appreciate your helping me here

![image](https://user-images.githubusercontent.com/53085438/173203481-807175ab-5ed1-40b2-897b-71d9e6c7fcda.png)

**Comment by ggandor** [comment]
That should work, the problem is that lightspeed (the module) itself is not found. How did you install it (e.g. using vim-plug)?

**Comment by Muzzamil1** [comment]
I have installed it using Plug (vim-plug) - plugin manager

![image](https://user-images.githubusercontent.com/53085438/173242751-dcfa85a8-b1b3-4cc4-bd81-92d84466a9c5.png)

It is working fine when I press "s" not sure why it says ` module 'lightspeed' not found:`  when I try to change the setting.

![image](https://user-images.githubusercontent.com/53085438/173242779-73949c0f-f8a6-4eda-9b54-d621da51e163.png)

**Comment by Muzzamil1** [comment]
Oh sorry, my bad. `plug#begin() ... plug#end()` was after that setting. Putting it before worked perfectly. Thank you so much for your help.
