### ISSUE TITLE
Failing to set keybind overrides

### ISSUE THREAD

**Issue by sQVe** [ggandor/lightspeed.nvim#15]
Hey 👋🏼,

I'm trying to run the following config:

```lua
--  ╻  ╻┏━╸╻ ╻╺┳╸┏━┓┏━┓┏━╸┏━╸╺┳┓
--  ┃  ┃┃╺┓┣━┫ ┃ ┗━┓┣━┛┣╸ ┣╸  ┃┃
--  ┗━╸╹┗━┛╹ ╹ ╹ ┗━┛╹  ┗━╸┗━╸╺┻┛
return function()
    require('lightspeed').setup {
        jump_to_first_match = false,
        cycle_group_fwd_key = '<tab>',
        cycle_group_bwd_key = '<s-tab>'
    }
end
```

but the `cycle` keybind overrides are not working.  Strangely the default <kbd>Space</kbd> is no longer working either. This must be a bug, no? 🐛 🔨 

A minor thought is that I find it somewhat strange that a option alters the default keymap. What's the reasoning behind this?

**Comment by ggandor** [comment]
Thanks very much for reporting! The problem is about the keycodes (if you write `" "` instead of `<space>`, that works), those are not translated if coming from the user-overridden `opts` field. Fixing this right now.

**Comment by ggandor** [comment]
Also, it has just occurred to me that `<s-space>` is problematic in some environments (terminals, but apparently also in nvim-qt), so I think we need to change that, e.g. to `<tab>`.

**Comment by sQVe** [comment]
Yeah. I was actually just going to add that @ggandor. <kbd>Shift+Space</kbd> is rough in a terminal.

**Comment by ggandor** [comment]
> A minor thought is that I find it somewhat strange that a option alters the default keymap. What's the reasoning behind this?

That is because group-switching is in fact not a separate call. We are processing the whole window at once, and are inside `s:to` the whole time. We get the labels and the cycle key via the same `getchar()` call - if it's a cycle key, then we're doing a new highlighting round, but using the same data structure (containing the matches).
