### ISSUE TITLE
fatal: invalid reference: master when Installing or Updating with vim-plug

### ISSUE THREAD

**Issue by thesofakillers** [ggandor/lightspeed.nvim#153]
Happens when calling :PlugInstall or :PlugUpdate

I've tried uninstalling and reinstalling, to no avail

<img width="272" alt="Screenshot 2022-07-05 at 12 52 37" src="https://user-images.githubusercontent.com/26286291/177312361-63cda10d-114d-4848-b345-c9e9b5882369.png">

Weirdly, despite the "fatal" error message, the installation seems to be successful, i.e. i am able to use lightspeed.nvim

**Comment by ggandor** [comment]
This is an issue of vim-plug, I guess it behaves the same way with all repos having a `main` branch as default. Try to update vim-plug itself. (See https://github.com/junegunn/vim-plug/issues/1005 and all the related issues. Also, https://github.com/glepnir/zephyr-nvim/issues/3 might help.)
