### ISSUE TITLE
Problems when setting safe_labels = {}

### ISSUE THREAD

**Issue by yyy33** [ggandor/lightspeed.nvim#155]
This is my config file 
```
require'lightspeed'.setup {
    exit_after_idle_msecs = { labeled = nil, unlabeled = 0 },

    jump_to_unique_chars = { safety_timeout = 0 },

    match_only_the_start_of_same_char_seqs = true,

    safe_labels = {},

    limit_ft_matches = 0
}

vim.g.lightspeed_no_default_keymaps = 1

vim.keymap.set({'n', 'x'}, 's',  '<Plug>Lightspeed_s',   {silent = true})
vim.keymap.set({'n', 'x'}, 'S',  '<Plug>Lightspeed_S',   {silent = true})
vim.keymap.set({'n', 'x'}, 'gs', ' <Plug>Lightspeed_gs', {silent = true})
vim.keymap.set({'n', 'x'}, 'gS', ' <Plug>Lightspeed_gS', {silent = true})
vim.keymap.set({'n', 'x'}, 'f',  '<Plug>Lightspeed_f',   {silent = true})
vim.keymap.set({'n', 'x'}, 'F',  '<Plug>Lightspeed_F',   {silent = true})
vim.keymap.set({'n', 'x'}, 't',  '<Plug>Lightspeed_t',   {silent = true})
vim.keymap.set({'n', 'x'}, 'T',  '<Plug>Lightspeed_T',   {silent = true})

vim.g.lightspeed_last_motion = ''
vim.cmd [[
    augroup lightspeed_last_motion
        autocmd!
        autocmd User LightspeedSxEnter let g:lightspeed_last_motion = 'sx'
        autocmd User LightspeedFtEnter let g:lightspeed_last_motion = 'ft'
    augroup end
]]
vim.keymap.set({'n', 'x'}, ';',  [[g:lightspeed_last_motion == 'sx' ? "<Plug>Lightspeed_;_sx" : "<Plug>Lightspeed_;_ft"]],   {expr = true})
vim.keymap.set({'n', 'x'}, ',',  [[g:lightspeed_last_motion == 'sx' ? "<Plug>Lightspeed_,_sx" : "<Plug>Lightspeed_,_ft"]],   {expr = true})
```

This is test text
```
package main

import (
	"os"
	help "translateHelpDoc/help/vim"
	"translateHelpDoc/log"

	"github.com/alecthomas/kong"
)

func main() {
	log.SetLevel(log.DebugLevel)
	f, _ := os.Create("aa")
	log.SetOutput(f)
	ctx := kong.Parse(&CLI{})
	err := ctx.Run()
	log.FatalWithCheck(err)
}

type CLI struct {
	Data  string   `flag:"" required:"" short:"d" help:"Directory for saving translation results"`
```

1. My cursor at the beginning of the file with
![2022-07-14_12-27](https://user-images.githubusercontent.com/51548147/178899580-24ee7852-6759-4388-81b6-50b5bdf4c229.png)

2. When I type `sogf`, my cursor is at line 12
![2022-07-14_12-28](https://user-images.githubusercontent.com/51548147/178899701-6bb4c0fe-a69b-4822-b2a8-dbe72fde42be.png)

3. I type `;` multiple times, the cursor is at the last `og` in the screen, which is line 17
![2022-07-14_12-28_1](https://user-images.githubusercontent.com/51548147/178899908-5acb8be3-3237-4ee9-b1d6-5bcda15039f2.png)

4. After I typed `,`  multiple times, the cursor finally came to the 12th line and couldn't go back, normally it should go back to the `og`  of the 6th line
![2022-07-14_12-29](https://user-images.githubusercontent.com/51548147/178900327-c981b6d8-f834-452c-928e-adf15680632e.png)

5.When I don't set the `safe_labels = {}` option, everything works fine

**Comment by ggandor** [comment]
There is no bug here: `,`/`;` do not behave like `,` and `;` in vanilla Vim. You can only go back to the "start point" (where you first pressed `;`), but not beyond - it is like pushing and popping from a _stack_. 

The reason why it works like this is briefly mentioned in the Readme (`;/,` works the same way as `S/F/T`):

> S, F and T, on the other hand, always _revert_ the previous repeat. Note that in the case of T (or X, if mapped), this results in a different, and presumably more useful behaviour than what you are used to in clever-f and Sneak: it does not repeat the search in the reverse direction, but puts the cursor back to its previous position - _before_ the previous match -, allowing for an easy correction when you accidentally overshoot your target.

What this means in practice, regarding your example:

If you have safe labels, you will auto-jump to the first target, and that will be the start point for `;/,`. If you set `safe_labels = {}`, you will not auto-jump, so if you press a label, then you actually _exit_ the plugin. If you jumped to the second match (by pressing `f`), then the match _after that_ will be the start point if you now start a `;/,` sequence.
