### ISSUE TITLE
Configurable delay/timeout for f motions

### ISSUE THREAD

**Issue by serhez** [ggandor/lightspeed.nvim#158]
The current timeout for `f` motions before you can't press `f` again to keep jumping to the next character (`clever-f` style) feels too short personally. I stress a bit when I use this feature because I feel the timeout is going to be triggered.

Could this be a configurable attribute in the `setup()`?

Thanks!

**Comment by ggandor** [comment]
It can be configured - `exit_after_idle_msecs.unlabeled` includes f/t. Now that you mention it, I think I will disable the default timeout for f/t too, and make it opt-in.
