### ISSUE TITLE
Newly installed lightspeed.nvim throws error. Doesn't override nvim defaults.

### ISSUE THREAD

**Issue by diningPhilosopher64** [ggandor/lightspeed.nvim#161]
After installing lightspeed, when I open a new instance of lunarvim ( wrapper for neovim ). I'm seeing the following error

```bash
 Error detected while processing /home/sourabh/.local/share/lunarvim/site/pack/packer/start/lightspeed.nvim/plugin/init.lua:
E5113: Error while calling lua chunk: ...m/site/pack/packer/start/lightspeed.nvim/plugin/init.lua:26: attempt to index field 'keymap' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/lightspeed.nvim/plugin/init.lua:26: in main chunk
```

Because of the above error, the neovim defaults such as `s` is not being overridden by the lightspeed plugin. 

Other help related options provided in Readme.Md aren't working too.

Screenshot of the error mentioned above:
![image](https://user-images.githubusercontent.com/12293878/188301492-f0f044cd-dbd0-420a-b1cd-0b4b82053a7e.png)

**Comment by ggandor** [comment]
The problem is that the `vim.keymap.set` function is not available. You should check the Neovim version (0.7.0 should be okay).

**Comment by diningPhilosopher64** [comment]
Thank you!
