### ISSUE TITLE
automatically exit f/F

### ISSUE THREAD

**Issue by max397574** [ggandor/lightspeed.nvim#169]
After f/F lightspeed just stays in this mode (where you jump to the next match with fF and the matches are highlighted) until you press something except fF
it would be cool if there would be a configurable time to automatically exit this

**Comment by ggandor** [comment]
https://github.com/ggandor/lightspeed.nvim/blob/a5b79ddbd755ac8d21a8704c370b5f643dda94aa/doc/lightspeed.txt#L176-L180

**Comment by max397574** [comment]
I'd like this for f/t only though

**Comment by ggandor** [comment]
What's the point in that? From a UI perspective, the question is whether there are labels or not (for the former, one might need more time to process them).
