### ISSUE TITLE
Cursor color changing when lightspeed is active

### ISSUE THREAD

**Issue by sQVe** [ggandor/lightspeed.nvim#17]
👋🏼,

I explicitly set my cursor color in `alacritty` which help me track it. The cursor color changes when `lightspeed` is activated though - which is very confusing to me and I have a really hard time seeing where my cursor is.

Not active:
![2021-06-28_12-31](https://user-images.githubusercontent.com/2284724/123622953-2f058f00-d80d-11eb-874f-ae748ed2c7df.png)

Active: 
![2021-06-28_12-31_1](https://user-images.githubusercontent.com/2284724/123622965-32991600-d80d-11eb-8d3c-6e1dc3b3f78f.png)

This is highly noticable when using <kbd>t</kbd> or <kbd>f</kbd> repeatedly. The cursor color changes depending on the syntax highlighting and it's just confusing...

Is there an option to disable this or is it possible to add one? 🙏🏼

**Comment by ggandor** [comment]
Yep, I noticed this. It _could_ be disabled easily, but then you won't see the cursor at all :) You see, while Lightspeed is active, `getchar` calls are active, and that means the cursor is in fact down on the command line (you can see that too). It is just a hack that we are highlighting the original position, and we're using the `Cursor` highlight group for that (obviously). So ultimately it depends on the color scheme, some of them work fine, some others have issues like this. I've been thinking about this, not sure what else can we do on our side.

**Comment by ggandor** [comment]
On the other hand, you could think of this as a feature too: the different cursor color is like a "Lightspeed active" sign.

**Comment by sQVe** [comment]
This is easily fixed. I just set the `Cursor` highlight to mimic what settings I have in `alacritty`:

```lua
    -- Cursor.
    vim.cmd([[
        hi! Cursor guifg=#282828 guibg=#ebdbb2 gui=NONE cterm=NONE
    ]])
```

Cursor now behaves and is colored exactly the way I want it!

![image](https://user-images.githubusercontent.com/2284724/123626848-9291bb80-d811-11eb-9d4d-c7ff6ea94422.png)

**Comment by ggandor** [comment]
I'm re-opening this too, I'd like to address this issue in the readme.
