### ISSUE TITLE
how to begin troubleshooting if plugin does not seem to have mapped keys?

### ISSUE THREAD

**Issue by ipsod** [ggandor/lightspeed.nvim#171]
I want to try this plugin, but, after installing, it still does not work.  `:checkhealth` shows no mapping conflicts.  I tried moving it to the top and the bottom of my `Plug` list.  I tried adding the config to my .vimrc inside of `lua << EOF` ... `EOF` tags, but it threw errors, and I don't think I have time to learn how to use nvim with Lua right now.

**Comment by ggandor** [comment]
Do a sanity check with `:nmap s`, `:nmap S`, etc., that will show you if those keys are already remapped to something (in that case, Lightspeed will not overwrite those)

**Comment by ipsod** [comment]
That helped, thanks!
