### ISSUE TITLE
Tui support for highlighting

### ISSUE THREAD

**Issue by JBenda** [ggandor/lightspeed.nvim#2]
The Highlighting groups don't provide any `cterm` definitions for the TUI.
I found in `lua/lightspeed.lua` around line 175 the definition of the highlight groups

Is a target of this project to support TUI too?, then I could open a PR with my changes to discuss a possible implementation.

**Comment by ggandor** [comment]
Sure, we just need to add the corresponding `cterm` attributes to the group definitions. The question is, should we convert the values to 256 colors then? Or maybe 16?

The .lua file is generated, you can find the relevant part in the Fennel source file [here](https://github.com/ggandor/lightspeed.nvim/blob/main/fnl/lightspeed.fnl#L151).

**Comment by JBenda** [comment]
Thanks, I was already wondering how you possibly can keep track of all this `_16_` ;)
NeoVIM only supports 16 colors for console because of compatibility.

**Comment by JBenda** [comment]
In #4 is a simple idea how a solution looks like.
It's mirrored what I have changed in the `lightspee.lua` to make it work on my machine.

**Comment by ggandor** [comment]
Thank you :) Will look at this tonight, test and tweak the colors, and figure out a good scheme for light background...

There is a makefile included that you could use to compile the Fennel file to the lua folder, just run `make` after finishing the edits, and then the plugin can be tested locally after re-sourcing.

**Comment by JBenda** [comment]
Good to know, I never worked with Lua or Fennel before ^^

**Comment by clason** [comment]
Might I suggest just defining `LightspeedFoo` highlight groups and letting color schemes / user configs sort out the actual colors? This might be more portable / extensible and is how, e.g., `gitsigns` does this.

**Comment by ggandor** [comment]
> Might I suggest just defining `LightspeedFoo` highlight groups and letting color schemes / user configs sort out the actual colors? 

Preaching to the choir: `:h lightspeed-highlight`.

> (Also, TUIs _do_ use `guifg` if `termguicolors` is set.)

Yeah, that's why I skipped defining `cterm` groups, but it would be better to provide defaults for those anyway.

**Comment by JBenda** [comment]
> (Also, TUIs _do_ use `guifg`  if `termguicolors` is set.)

but this settting breaks many plugins ^^
