### ISSUE TITLE
Is it possible to customize the keys that are used for the hints?

### ISSUE THREAD

**Issue by IndianBoy42** [ggandor/lightspeed.nvim#21]
Right now it seems to use `s,f,n,/,t,g` and the shifted forms of those, maybe more. I suppose because those keys are associated with searching before. but they are also all over the place, I was thinking that using home row keys (starting from index finger and going out) should be better. At least for me, thats why I wondered if there is a config option yet?

**Comment by IndianBoy42** [comment]
I'm blind, its right there

**Comment by ggandor** [comment]
If `jump_to_first_target` is on, we should use use hints/labels that you wouldn't use right after a jump. If that is switched off, then the plugin automatically switches to home row keys.

**Comment by IndianBoy42** [comment]
I understand now, thanks, love the plugin

**Comment by giluis** [comment]
@ggandor but is there any way to not use the /?
It is kind of a bothersome key to type

**Comment by ggandor** [comment]
@giluis You can use your custom list of labels by setting `opts.labels`, simple as that (`:h lightspeed-config`).

As for not using two-key labels, that is a conscious design decision. From the Readme: "Note that Lightspeed keeps the invariant that a label consists of exactly one character, that should always stay in the same position, once appeared. (No rolling/flashing sequence of labels, like in case of Hop/EasyMotion.)"

If we'd use 2-char labels, and show them right away, that would be a mess. `[ab][cd][ef]` labels might appear next to each other then, and you could not distinguish between the matches. On the other hand, if we'd give the "primary" (`ace`) and "secondary" (`bdf`) characters different colors, that would also add another layer of complexity to the already complex highlighting scheme, and would make it much harder to comprehend (in some cases on the verge of total chaos I'd say). Moreover, one character as a label/hint (regardless of the typing effort), is quicker to process than two separate characters, that is also a major reason. If we don't have enough labels, we just put the remaining matches into the `tab/space` (secondary) group. This way you don't have to process another label in your head, just automatically prefix the label with the switch key, that is much easier on your brain.

**Comment by giluis** [comment]
Thank you so much for the explanation!
I understand why two character labels are not a great idea in this context.
As for the / character, I cannot find `opts.labels` anywhere when i do `:h lightspeed-config`
![screenshot of unsuccessful search](https://user-images.githubusercontent.com/52404649/134503191-02cf92ab-6b98-4b25-bcda-f34e96b50ed4.png)

Am I missing something?

**Comment by ggandor** [comment]
Check the "Available options" section below that illustrative snippet ([here](https://github.com/ggandor/lightspeed.nvim/blob/6ca32a155406d11093f64fa97e0ba8c6802fb7e1/doc/lightspeed.txt#L207)). But basically just do `lua require'lightspeed'.opts.labels = { 'a', 'b', 'c', ... }`, or the same via `setup`.
