### ISSUE TITLE
A way to map repeat `s` motions? (Hopefully with `;`/`,` as well)

### ISSUE THREAD

**Issue by talw** [ggandor/lightspeed.nvim#25]
Thanks for this plugin!

Just like there is [a way to map ; and , (or custom keys) to repeat f/t motions](https://github.com/ggandor/lightspeed.nvim/issues/3), is there a way to map keys to repeat `s` (2-key) motions? If not, is there a way to repeat them at all? perhaps, by pressing `s` again?

It isn't currently documented and I tried to do it myself adhoc by adjusting the example for `ft` but from looking at the code, the `ft` and the `s` tables aren't exactly identical so I couldn't simply adjust the code in the documentation to apply to `s`.

I wonder if it's just a niche use-case? I'm using 2-key motions for everything; same line, next line or across half a screen. I find that the cost of pressing the second character is almost zero and the benefits it brings in disambiguation to reduce the number of matches is big.  I also have jump-to-first-match enabled.

Thanks again!

**Comment by ggandor** [comment]
> I'm using 2-key motions for everything; same line, next line or across half a screen. I find that the cost of pressing the second character is almost zero and the benefits it brings in disambiguation to reduce the number of matches is big.

Totally agree, I rarely use `f/t`, except for operations (quickly `df`-ing something in the proximity, stuff like that).

> I wonder if it's just a niche use-case?

I've been thinking a lot about whether I should support this too. The question is, what's the use case here? Do you want to repeat right away (i.e., you'd like to have an "instant-repeat" feature for 2-char search too, not having to use labels to reach a target, just press `;;;` mindlessly), or repeat the search sometime later?

The first case is very simple: you can map dedicated keys to `<Plug>Lighspeed_s/S<cr>`. In fact, this also works as a quick and dirty hack for the second case - the "flashing" labels are a bit annoying though, as this will relabel the whole area at every step.
```
nmap ; <Plug>Lightspeed_s<cr>
nmap , <Plug>Lightspeed_S<cr>
```
Do you happen to have some good use cases in mind where this latter behavior - instant-repeating - would be truly useful? It would require just a little bit of hacking I guess, but I'm not convinced about the feature yet. The whole point of the plugin and its ahead-of-time labeling is that you can rely on labels now, without (or with minimal) disruption.

**Comment by talw** [comment]
Thanks for your quick reply!

> or repeat the search sometime later?

> The second case is very simple: you can map dedicated keys to `<Plug>Lighspeed_s/S<cr>`. In fact, this works fine as a quick and dirty hack for the first case too - the "flashing" labels are a bit annoying though, as this will relabel the whole area at every step.

Just to make sure I understand you correctly, to repeat the search in this case, one has to not just press `s` but also the extra 2 keys as well, correct? Or is there a way I am missing to repeat it without those 2 extra presses?

If by "sometime later" you mean something along the scope of tens of seconds upward, then I agree that
repeating the search anew is no problem. And I am using a dedicated key by the way, it is mapped to `f` ;)
(i.e. no more 1-key jumps for me), but to avoid confusion I am refering to it as `s`.

> I've been thinking a lot about whether I should support this too. The question is, what's the use case here? Do you want to repeat right away (i.e., you'd like to have an "instant-repeat" feature for 2-char search too, not having to use labels to reach a target, just press `;;;` mindlessly), 

> Do you happen to have some good use cases in mind where this latter behavior - instant-repeating, without labeling - would be truly useful? It would require just a little bit of hacking I guess, but I'm not convinced about the feature yet. The whole point of the plugin and its ahead-of-time labeling is that you can rely on labels now, without (or with minimal) disruption. Also, `s/S` is not really for macro-like, repetitive editing tasks - IMHO, for those you'd better use the normal `/?*#` search commands, that allow for more precision (in that case, the speed gain for the initial search by Lightspeed `s/S` is negligible/irrelevant anyway). But I'm happy to hear any good counter-arguments!

Indeed it is for instant repeating.

Perhaps I got used to sneak.vim's `;` repeat that works for 2-key search and jumps to the following matches further down the screen.

It might sound odd at first but it is to do an interactive find and replace.

I could roughly split find and replaces to deliberate and indeliberate cases.

In the case of an indeliberate find and replace, I jump somewhere do some change
and only then the intention to propagate this change occurs, and then I would like to do (used to do with `sneak.vim`), for example, `;.;.;.` to repeat the change quickly, sometimes skipping some matches, like `;.;;;.;;.`.

In the case of a deliberate find and replace, I could use `/`, `<CR>` and `n` instead, at the cost of potentially getting out of the zone beause I have to be cognizant of two ways of jumping to specific places.

- I find it cumbersome because of the `<CR>` at the end of the search string,
  and the key press to ":nohl" afterwards in the end.
- I find it slower because I have `smartcase` enabled, which means that it
  requires more keys to pinpoint the search whereas `lightspeed.nvim` is case sensitive. In that case you could suggest I disable `smartcase` but I do want it on as my use for `/` is for a search of something I am not completely sure about, even if it isn't a regex, it is helpful not to search both upper and lowercase options when using "/", for this reason.

However, in the case of less-than-trivial find and replaces, especially those involving a regex or more than say 3-4 replaces, I agree there is no gain to be had by using `lightspeed.nvim`, but most of my repetitive editing cases are trivial changes to no more than 3-4 instances of some text.  And in the case of a more involved find and replace I am down a couple of flow notches anyway.

Another distinction is that when I am jumping to somewhere that I am not looking at, I use "/", and when I jump to somewhere I am looking at, I use `lightspeed.nvim`.  For the simple find and replace, I am looking at the first match, but for the second/third/fourth replaces I don't search them with my eyes, I press `;` and let that grab my attention.  If that makes sense.

(bonus) As a somewhat less subjective reason, I think it will make `s` and `f` a bit more symmetrical :)

**Comment by gegoune** [comment]
There is `c` flag for `:s` which does exactly what you are describing. `:s/foo/bar/c` will jump between matches and prompt you whether you want to apply replacement.

**Comment by ggandor** [comment]
> Just to make sure I understand you correctly, to repeat the search in this case, one has to not just press s but also the extra 2 keys as well, correct? Or is there a way I am missing to repeat it without those 2 extra presses?

No, this is a fully functioning workaround - pressing `<enter>` repeats the previous search for any of the commands, that is a built-in feature. So you just have to map `s<cr>`  (or the original `<Plug>...<cr>`) to something, and there you have your instant repeat. (The labeling - that cannot be turned off, as of now - is the only minor annoyance, as I mentioned.)

As for the rest, there's some food for thought there. Meditate on this, I will. :D

**Comment by talw** [comment]
> There is `c` flag for `:s` which does exactly what you are describing. `:s/foo/bar/c` will jump between matches and prompt you whether you want to apply replacement.

Sorry @gegoune my comment was a bit misleading, I did say "interactive find and replace" but I was not referring to the kind you kindly mentioned in your comment.

Thanks for the suggestion 🙏

**Comment by talw** [comment]
> > Just to make sure I understand you correctly, to repeat the search in this case, one has to not just press s but also the extra 2 keys as well, correct? Or is there a way I am missing to repeat it without those 2 extra presses?
> 
> No, this is a fully functioning workaround - pressing `<enter>` instead of giving a search pattern repeats the previous search for any of the commands, that is a built-in feature. So you just have to map `s<cr>` (or the original `<Plug>...<cr>`) to something, and there you have your instant repeat. (The labeling - that cannot be turned off, as of now - is the only minor annoyance, as I mentioned.)

@ggandor That is interesting! I have a feeling I tried <CR> before and nothing happened but I may be confusing with something else, I shall try this tomorrow and see how it goes!

**Comment by talw** [comment]
> > Just to make sure I understand you correctly, to repeat the search in this case, one has to not just press s but also the extra 2 keys as well, correct? Or is there a way I am missing to repeat it without those 2 extra presses?
> 
> No, this is a fully functioning workaround - pressing `<enter>` instead of giving a search pattern repeats the previous search for any of the commands, that is a built-in feature. So you just have to map `s<cr>` (or the original `<Plug>...<cr>`) to something, and there you have your instant repeat. (The labeling - that cannot be turned off, as of now - is the only minor annoyance, as I mentioned.)
> 
> As for the rest, there's some food for thought here. Meditate on this, I will. :D

I tried it, and it does work somewhat but not ideal :)
There is the flashing lights which makes the cursor stand out less, but also it doesn't continue past where the screen currently is (not that I plan for it to scroll downwards that much), in contrast with your repeating `f` which does continue downwards.

Even without this implemented however, I still think it's a great plugin :)

**Comment by ggandor** [comment]
> In the case of an indeliberate find and replace, I jump somewhere do some change and only then the intention to propagate this change occurs, and then I would like to do (used to do with sneak.vim), for example, ;.;.;. to repeat the change quickly, sometimes skipping some matches, like ;.;;;.;;..

Okay, this is a very rare situation I guess. I mean, when you somehow forget that you want to propagate the change, but it's early enough that you hasn't done another edit, so the change is still in `@.`

It might still be beneficial to just switch to `*`, because you potentially has to skip a lot of false posivites in-between, if you're repeating the 2-char search pattern.

> do #*, and go back to the first match with the opposite key
```Vim
" The * will stay on the current instance (stolen from Steve Losh's config)
nnoremap <silent> * :let view = winsaveview()<cr>*:call winrestview(view)<cr>
```
Also, one should usually use `{op}gn`, in these cases, so after landing on the target, you can just press e.g. `*cgn....` for changing 4 instances of the word under the cursor, instead of `*ciwn.n.n.n.` That is a very neat trick, see `:h gn`.  With repeating 2-char search, it is not possible.

> and the key press to ":nohl" afterwards in the end.

Yeah, that could be annoying, I have already mapped `<esc>` (which is of course CapsLock) to `:noh` in Normal mode.

> in contrast with your repeating f which does continue downwards.

No, it does not... If `scrolloff` is set to > 0, then it might go vertically off-screen in a kinda unintended way, but the same is true for `s/S`. (Actually, `f/t` shouldn't go into folded areas either, but somehow I decided to allow it by default. However, `f/t` should definitely be able to go horizontally offscreen on non-wrapped lines, because we might record a macro, or execute a `:normal` command.)

> As a somewhat less subjective reason, I think it will make s and f a bit more symmetrical :)

That's the point, I don't _want_ them to be symmetrical :) For f/t, it is natural to provide either "clever-f" functionality, or `;`/`,`, because for those, the targets cannot be labeled ahead of time anyway. But I don't want to encourage inefficient patterns/behaviors, and induce the "having a hammer, everything looks like a nail" syndrome. `/?` has all kinds of supporting stuff, there is almost a mini-DSL for search and replace in Vim, with which we cannot - and should not - compete. There are shortcuts for repeat (`//`, `/~/`, `/&`, `:s`, `:&`, `:s//~/`, `&`, `g&`), offsets (`:h search-offset`), the above mentioned `gn`/`gN`, etc. etc. We should come up with additional mappings or helper functions then, that encapsulate common patterns and allow this DSL to be used even more efficiently. Lightspeed is for jumping from A to B.

Anyway, this is just my current view on things, feel free to discuss this further here.

**Comment by talw** [comment]
> > do #*, and go back to the first match with the opposite key
> 
> ```viml
> " The * will stay on the current instance (stolen from Steve Losh's config)
> nnoremap <silent> * :let view = winsaveview()<cr>*:call winrestview(view)<cr>
> ```
> 
> Also, one should usually use `{op}gn`, in these cases, so after landing on the target, you can just press e.g. `*cgn....` for changing 4 instances of the word under the cursor, instead of `*ciwn.n.n.n.` That is a very neat trick, see `:h gn`. With repeating 2-char search, it is not possible.

Wow, I did not know those two tricks, but they work really great!

> No, it does not... If `scrolloff` is set to > 0, then it might go vertically off-screen in a kinda unintended way, but the same is true for `s/S`. (Actually, `f/t` shouldn't go into folded areas either, but somehow I decided to allow it by default. However, `f/t` should definitely be able to go horizontally offscreen on non-wrapped lines, because we might record a macro, or execute a `:normal` command.)

You are correct!  Sorry for the mistake.

> That's the point, I don't _want_ them to be symmetrical :) For f/t, it is natural to provide either "clever-f" functionality, or `;`/`,`, because for those, the targets cannot be labeled ahead of time anyway. But I don't want to encourage inefficient patterns/behaviors, and induce the "having a hammer, everything looks like a nail" syndrome. `/?` has all kinds of supporting stuff, there is almost a mini-DSL for search and replace in Vim, with which we cannot - and should not - compete. There are shortcuts for repeat (`//`, `/~/`, `/&`, `:s`, `:&`, `:s//~/`, `&`, `g&`), offsets (`:h search-offset`), the above mentioned `gn`/`gN`, etc. etc. We should come up with additional mappings or helper functions then, that encapsulate common patterns and allow this DSL to be used even more efficiently. (And/or use plugins like vim-subversive, or even better, LSP/Treesitter-aided solutions.) Lightspeed is for arbitrary jumps between A and B.
> 
> Anyway, this is just my current view on things, feel free to discuss this further here. :)

You make a very good point.
I think I may have gotten used to a sub-optimal workflow precisely because `sneak.vim` allowed to have those repeatable jumps for 2-character searches.

The points you make and the tricks you taught me make perfect sense, now it is just a matter of getting used to them.
I agree with your approach so I will close this issue.  If it is desired by anyone that I reopen this, I will.

Thanks again!

**Comment by ggandor** [comment]
Thanks, glad to hear it was useful! Also, these arguments might be worth adding to the "Why no feature X..." section of the Readme.

**Comment by talw** [comment]
> Also, these arguments might be worth adding to the "Why no feature X..." section of the Readme.

Whichever you feel is right!

**Comment by ggandor** [comment]
Screw it, I will just implement this. I've already implemented "proper" `;`/`,` repeat for `ft`, and it's not much code, pretty clean actually. So even though this might only rarely be useful, the leverage is still high enough I guess.

**Comment by talw** [comment]
@ggandor Cool, thanks!

I wonder what changed your mind?

**Comment by ggandor** [comment]
@talw We're talking about shortcuts for what I call - for lack of a better term - "cold" repeat in the codebase now. For `ft`, it is native, even though it's quite useless when one has a dedicated "instant" repeat option already. But if we have `ft` + cold-repeat, then `sx` + cold-repeat is actually _a bit_ more useful. Also, it's true that 10/1 cognitive load + "quite fast" just feels better sometimes than 10/3 cognitive load + maximal speed; this is why one just likes to press `wwwwwww` when _really_ immersed in a task. I mapped them to `<a-;>` and `<a-,>` for now, and I think they have some potential. Especially once I implement labeling for this (would work the same, but you can also directly jump to a distant match). For this mode, I'm also thinking about underlining/highlighting the occurrences of the word (or WORD) that was targeted by the original search.

**Comment by talw** [comment]
@ggandor 

Indeed, you have a point.
Thanks!
