### ISSUE TITLE
Turn off scrolloff while lightspeeding?

### ISSUE THREAD

**Issue by xigoi** [ggandor/lightspeed.nvim#27]
After pressing the second character, `lightspeed` immediately jumps to the first match. Unfortunately, if one has `'scrolloff'` activated, this may cause the screen to scroll, making it hard to keep focus on the remaining labels. Would it be possible to temporarily disable the setting?

**Comment by ggandor** [comment]
Absolutely, good idea, I use `scrolloff` too, but haven't thought about this yet. I will fix this soon.

**Comment by ggandor** [comment]
Sidenote: a pending Neovim [issue](https://github.com/neovim/neovim/issues/13964) complicates this - we could hack around it, or just wait for it to be resolved. :)

**Comment by ggandor** [comment]
Food for thought: I've implemented this, but when we want to target to the _first_ match, it is just as annoying that on the next command, the window suddenly scrolls...
