### ISSUE TITLE
Semicolon (;) and Comma (,) repeats not working when mapping with : instead of <CMD>

### ISSUE THREAD

**Issue by kvietcong** [ggandor/lightspeed.nvim#30]
Hi, this is a relatively small issue but when changing the command triggers found in the help for ; and , repeating, it stops working in visual mode. (Changing the `<cmd>` to `:`). When trying to use ; or , in visual mode, it doesn't expand the selection after the first search with f or t. However, it works fine when I do what the help says. I'm not sure if this is a Neovim or Lightspeed issue so if it doesn't seem like a Lightspeed issue (or if it's a non-problem) feel free to just resolve this.

Thank you

**Comment by ggandor** [comment]
Hello! Indeed, but this is exactly what `<cmd>` is for: when used in a function, it does not change the mode we're in, as opposed to `:` (see `:h <Cmd>`). The latter would require modifications in the plugin itself (re-selecting the  visual selection, after it disappears). So this is not an issue/bug per se, but a feature that we're using.

**Comment by kvietcong** [comment]
Got it, thanks for the clarification. I just found it a bit weird that `:` still works in almost every way except for visual mode lol

Thank you so much for making such a great plugin though! Really feels like it adds on to Vim rather than making it into something different

**Comment by ggandor** [comment]
> Really feels like it adds on to Vim rather than making it into something different

I am really glad to hear such feedback - this is exactly the aim of the plugin (following the footsteps of Sneak), to provide a slick,  "should be default"-kind of experience. Thanks for the kind words!
