### ISSUE TITLE
Visual mode, 'S' for backward selection not working

### ISSUE THREAD

**Issue by benfrain** [ggandor/lightspeed.nvim#31]
Just installed and using standard config:

```
require("lightspeed").setup({})
```

In visual mode, using 's' to select forwards works as expected. However, 'S' from visual mode does not. It stays in Visual mode but does not enter 'lightpeed'.

**Comment by ggandor** [comment]
Hi there! I cannot reproduce this - I guess you have some custom mapping for `S` in Visual mode, probably by some other plugin (in that case, Lightspeed will not overwrite it). You can check it with `echo maparg("S", "v")`.

P.S.: After installation, there's no need to call `setup` at all, only if you'd like to change some of the default settings.

**Comment by benfrain** [comment]
@ggandor bah!!! Vim Surround!

Sorry to have wasted your time!

**Comment by ggandor** [comment]
Always glad to help :) ([I've anticipated this conflict](https://github.com/ggandor/lightspeed.nvim/commit/93d59054973cf2f85d374e6e05fbf79a2bea698d), but, well, "there can be only one".)

**Comment by benfrain** [comment]
Highlander 😁

**Comment by ggandor** [comment]
For Surround, I suggest mapping `S` -> `gs` in Visual mode (`xmap gs <Plug>VSurround`), that would actually be a [more consistent arrangement](https://github.com/justinmk/vim-sneak/issues/268#issuecomment-874687220).

**Comment by benfrain** [comment]
To be honest, using ‘s’ in normal mode is more of a problem for me as I tend to use that quite a lot. Will try ‘h/H’ instead for Lightspeed as I use Colemak and arrow keys rather than hjkl for navigation.

**Comment by ggandor** [comment]
In fact, if you're not using `h/j/k/l` anyway, then you are free to use `h/H` for Lightspeed in every mode, including operator-pending mode, and have a fully consistent mapping, that sounds awesome.

**Comment by ggandor** [comment]
On the other hand, `h` is a bit less comfortable than `s`... I've never considered `s` particularly useful, since it's == `cl`, and as an editing command, it is still a lot less frequent than the all-around jump motion (that should be the most comfortable mapping among all). Maybe the other way around, (native) `s` -> `h`? But I guess `s` is too ingrained in your muscle memory then. Well, it's your call of course, experiment :)

**Comment by benfrain** [comment]
> In fact, if you're not using `h/j/k/l` anyway, then you are free to use `h/H` for Lightspeed in every mode, including operator-pending mode, and have a fully consistent mapping, that sounds awesome.

I can think of it, semantically as, dare I say it, ‘Hop’ 😮

**Comment by ggandor** [comment]
> I can think of it, semantically as, dare I say it, ‘Hop’ 😮

:DDDDD

**Comment by EtiamNullam** [comment]
`vim-surround` is still useful in my opinion, but this remap is necessary to stay compatible and really seems more reasonable than the default:

> For Surround, I suggest mapping `S` -> `gs` in Visual mode (`xmap gs <Plug>VSurround`), that would actually be a more consistent arrangement for Surround itself.
