### ISSUE TITLE
Add Media to readme.md to Preview Functionality

### ISSUE THREAD

**Issue by kintsugi** [ggandor/lightspeed.nvim#34]
Title. I think it would improve user adoption rate based. A picture is worth a thousand words so for some of the more meatier plugins it really helped me understand their purpose when I was new to vim.

Willing/able to do this myself but I adopted this plugin today and need to familiarize myself.

If the decision is that this is not the right move then I'm still interested if anyone has something they want to show off to someone new.

**Comment by ggandor** [comment]
I'm a bit perplexed, [there are](https://github.com/ggandor/lightspeed.nvim/blob/main/README.md#-an-in-depth-introduction-of-the-key-features) animated gifs in the readme, showing 4 different features of the plugin, in action, with keystrokes shown on screen. Is there anything I could do to make things even more clear?

**Comment by ggandor** [comment]
I could insert the second gif right below the lead text too, so a visitor can see some visuals right away.

**Comment by ggandor** [comment]
Okay, if there are no further comments, I'm closing this.
