### ISSUE TITLE
Can't extend visual selection if (vim) windows show different buffers

### ISSUE THREAD

**Issue by TheBlob42** [ggandor/lightspeed.nvim#38]
If you have multiple (VIM) windows open which show different buffers `lightspeed` commands (s, S, f, t, F, T) will exit visual mode.

## Example

- open neovim
- split the current buffer `:sp`
- switch to visual mode and try e.g. `f i`, `f`, `f` etc.
    - The selection should be extended as one would expect
- switch one of the windows to another buffer
- switch to visual mode and try e.g. `f i`, `f`, `f` etc.
    - The cursor jumps but we're back in normal mode

![lightspeed](https://user-images.githubusercontent.com/6849129/130335242-14c40cf6-d342-4bd8-b488-1c8c350eba9e.gif)

<details>
  <summary>Minimal NVIM configuration used in the example</summary>
  
```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
local is_packer_installed = vim.fn.isdirectory(install_path) == 1
if not is_packer_installed then
    vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end

require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'ggandor/lightspeed.nvim'
end)
```
</details>

I have had a look in the code, but could not see what could cause this behavior :slightly_frowning_face:

**Comment by ggandor** [comment]
Yep, I can reproduce, unfortunately. This is a pretty serious bug, and at the moment I have absolutely no idea what could cause this, and when will I have the time to hunt it down.

**Comment by ggandor** [comment]
Okay, the good news is that this bug is not present in the older commits, so it's binary-searchable at least. I'm kinda relieved :)

**Comment by ggandor** [comment]
This is the one: https://github.com/ggandor/lightspeed.nvim/commit/d1084c0ac413d6ad1ed3ec290604e7e2fbe0aae1. It's about `:DoMatchParen` then. I will look into the source of matchparen again.

**Comment by TheBlob42** [comment]
I also had another look into the source of `lightspeed` and `matchparen` but did not really understand what could cause this exactly :slightly_frowning_face: 

However I could fix the issue (while keeping the original "remove the matchparen highlight"-functionality) by using the `:NoMatchParen` command instead of `:3match` to remove the highlight. But I have to admit that I have no clue why this works :see_no_evil: 

```fennel
(fn remove-matchparen-highlight []
  ; After autojumping to the first match, or to a unique char, the parens remain
  ; highlighted while our plugin is executing, even though the cursor has been
  ; moved.
  (when (= (vim.fn.exists ":NoMatchParen") 2)
    (vim.cmd :NoMatchParen)))
```

@ggandor maybe you understand this better than me

**Comment by TheBlob42** [comment]
I think I found the issue for what is happening.  
See this line from the visual mode documentation (`:h Visual`):

```text
If you use <Esc>, click the left mouse button or use any command that does a jump to another buffer
while in Visual mode, the highlighting stops and no text is affected.
```

When checking the source for the `DoMatchParen` command we can see that `windo` is used to activate the highlighting in all visible windows:

```vim
func s:DoMatchParen()
  runtime plugin/matchparen.vim
  let w = winnr()
  silent windo doau CursorMoved <-- this line here
  exe "noau ". w . "wincmd w"
endfunc
```

`windo` will navigate to every window of the current tabpage and execute the given command there (see `:h windo`). As soon as one of those windows is visiting another buffer than the current one the highlighting stops as stated in the visual mode documentation. That is the reason it works for splits showing the same buffer.

We could have a simple workaround to prevent this like the following:

```fennel
(fn force-matchparen-highlight []
  ; NOTE: :DoMatchParen overwrites the current dot-repeat setting,
  ;       that should be (re)set after this call!
  (let [mode (vim.fn.mode)] ; save current mode
    (when (= (vim.fn.exists ":DoMatchParen") 2)
      (vim.cmd :DoMatchParen)
      (when (or (= mode "v") (= mode "V") (= mode "CTRL-V")) ; if last mode was "visual"
        (vim.cmd "normal gv")))))                            ; restore selection
```

**Comment by ggandor** [comment]
Wow, you're invaluable :) I think this might also be the reason why it breaks dot-repeat (the selection is gone).

On the other hand, have you actually tried the workaround? I tried reselecting with `gv`, but that did not work for me. The visual selection is not updated at that point, apparently, it restores the previous state. (Though I don't really understand why.)

But again, we can do something simpler: let's not use `:DoMatchParen` at all, but trigger the refresh manually then, with `doautocmd CursorMoved`, for our window only. This is a very clean solution.

**Comment by TheBlob42** [comment]
No problem, I am always happy to help :slightly_smiling_face: 

For me it did work with `gv`, but never the less I like the solution using `doautocmd CursorMoved` way better. No need to "restart" `matchparen` for all open windows.
