### ISSUE TITLE
Allow custom characters as substitutes for highlighting whitespace characters (tab/space)

### ISSUE THREAD

**Issue by rktjmp** [ggandor/lightspeed.nvim#41]
It might be nice to be able to set stand-ins for characters in labels.

See in this attached screenshot, where I have run `vs0` from the start of the line (taken with Nord colorscheme so probably reasonably representative of many users):

![image](https://user-images.githubusercontent.com/866010/131801178-ca4bac80-534a-437a-a608-4ad7b87c0ac4.png)

Technically the first match is `0<space>`, which makes sense, but it can be easy to overlook, I naturally want to type `00` because my brain reads it as a shortcut jump. I know this is wrong but still it happens.

If I could specify `space_label = "˽"`, my brain might read it correctly.

![image](https://user-images.githubusercontent.com/866010/131801215-fcda5a12-a614-4965-9b89-88010e37f68c.png)

I don't really know what the complexity would be, I think it's totally serviceable as is, but maybe a nice to have?

**Comment by rktjmp** [comment]
Yeah, I think it's just my brain dreams the motion as "`goto {ch1}<foggy thoughts>`" not "`goto {ch1}{space}`" when I am looking at end of word characters. It's an entirely internal problem to me but probably bites other people too, or maybe I am a unique kind of dense :flushed:. (Also I just think `˽` *looks* cool...)

I can't really think of other characters you might want to look different, motioning to `<tab>` or `<cr>` seems unlikely/impossible.

Honestly, it's probably reasonable to just sit on the idea for a bit, see if anyone else happens to want it then you can at least gauge interest?

I will probably look at patching it myself but that might be a fair ways out.

**Comment by ggandor** [comment]
> It's an entirely internal problem to me but probably bites other people too

Fair enough, anything for the customer... 😉

> (Also I just think ˽ looks cool...)

I tend to agree.

> motioning to <tab> or <cr> seems unlikely/impossible

We can move to `<tab>` actually! And it shows the underlying `^I` character, _occupying two columns_, so if `tabstop` is set to 1, then things become a bit crowded, and in any case, the other character will appear out of place 😊. This really bugs my OCD now. But then `<tab>` should have its own substitute character, and here things start to become messy... 

> Honestly, it's probably reasonable to just sit on the idea for a bit

That's what I'll do, I guess... The original request is easy to implement, quite isolated, just a couple of lines, but this `<tab>` case bothers me now, let's ponder on this a bit.

**Comment by ggandor** [comment]
> But then `tab` should have its own substitute character

One problem is that `tab` doesn't have a standard [control picture](https://unicode-table.com/en/blocks/control-pictures/), as opposed to space. `␉` is ultra-ugly, and not really visible... we might use ↹... 

On another note, I'm not sure what problems would it cause in the first place if we overlay multibyte cars, like `˽` and `↹`, over `space` and `tab`.

**Comment by ggandor** [comment]
Sidenote: a workaround might be to set a background color for `LightspeedUnlabeledMatch`, then space would be visible. But that is far from ideal.

**Comment by rktjmp** [comment]
I use `»` in my listchars for tab. I don't think you need to provide any defaults though, just let users pick? I would assume multibyte chars would be fine when they render as one glyph but I would have to learn-by-doing with the code.

**Comment by ggandor** [comment]
Now I'd like to provide some defaults, because the issue with `tab` can be considered an actual bug if you think about it.

**Comment by ggandor** [comment]
Characters rendered in multiple screen columns is an orthogonal problem, I'll open another issue for it.
