### ISSUE TITLE
Error when using F when 'limit_ft_matches' is zero

### ISSUE THREAD

**Issue by jam1015** [ggandor/lightspeed.nvim#45]
When I set the line
```
lua require'lightspeed'.opts['limit_ft_matches'] = 0
```

And search with `F` or `f` (`Fa` or `fa`) for example and then try to reverse the search with `F` I get the warning `not found: [character typed]` and I have to press `F` twice for each reverse jump. The problem goes away when I set `limit_ft_matches` to a value of one or greater.  The problem does not occur using `T`.

**Comment by ggandor** [comment]
Yeah, I can reproduce, thanks for reporting!
