### ISSUE TITLE
Consider removing F/f/T/t search from lightspeed and splitting it into a different plugin

### ISSUE THREAD

**Issue by jam1015** [ggandor/lightspeed.nvim#46]
It is a good functionality that I've come to like.  There were some design decisions I wasn't sure of but after thinking about it I've come to like it.  But I think it would be more elegant/UNIX-philosophy compliant if this was in a separate plugin.  I know that someone who doesn't want these features can just unmap them but I think it is more elegant and maintainable to only add what you want to your config, as opposed to adding and removing. 

An alternative would be a boolean option of whether to include this functionality rather than making it the responsibility of the user to write unmaps.

**Comment by ggandor** [comment]
`1` The most important preliminary question here, that I always ask, is: why would you prefer the native f/t over Lightspeed's? What features do you miss, or which feature is a deal-breaker?

Splitting Lightspeed into two plugins would not really count as UNIX-ification IMO, it would just increase entropy. Let me explain.

**Conceptual integrity**
That proverbial "one thing" we "do well" here is covering the whole on-screen area with universal - that is, context/target independent - motions.  Enhanced `f/t` search is not like some additional feature that one may or may not need - _together_ with `s/x` they form a package that offers maximally efficient commands for every situation where there is no target-specific motion (`w`, `%`, `}`, etc.) available. Thus there is a strong overarching conceptual bound between them.

**Consistency**
The most important aspect of the "Unix way", in my understanding, is not merely "splitting things into smaller parts", but first and foremost enabling the _composition_ of the parts, and thus allowing for exponentially more flexibility. Extracting f/t out would have nothing to do with that (only if you'd want to use some other f/t-enhancing plugin, but `THEN GOTO 1`).  On the other hand, _consistency_ is also a feature, and its obviously much easier to maintain consistency between the behaviour/interface of motion commands if they are not living and evolving in their separate universes. It's probably not an accident that no one has raised an issue in the EasyMotion repo so far, requesting splitting it to 5+ different plugins, handling each of the motions separately.

**DRY**
 `f/t` and `s/x` use the same underlying machinery, a lot of non-trivial utilities, for finding the on-screen targets, highlighting etc. The choice would be between introducing common dependencies or violate DRY, obviously. (+ cf. the "consistency" section above)

**Comment by jam1015** [comment]
I know you've put a lot of thought and effort into how this plugin should work. I think that people coming from the outside don't have your comprehensive vision of the ideal way to move around in text, and already have their own deeply established ways of doing things.  So I actually use your f/t, but overall we can't say what every user wants, so it is more user-centric to give users simple options to turn things on or off, and let them see the overall conceptual bond between the two functionalities for themselves as they go along.
I do see how splitting the functionality to different packages when they rely on the same infrastructure could make things messy.  So maybe I think a Boolean option would be a good substitute for splitting out into a package. A good example of this user centricity is Hop's way of implementing functionality but letting users pick keybindings (even though I kind of wish that they had some preconfigured defaults).

**Comment by jam1015** [comment]
I know you've put a lot of thought and effort into how this plugin should work. I think that people coming from the outside don't have your comprehensive vision of the ideal way to move around in text, and already have their own deeply established ways of doing things.  So I actually use your f/t, but overall we can't say what every user wants, so it is more user-centric to give users simple options to turn things on or off, and let them see the overall conceptual bond between the two functionalities for themselves as they go along.
I do see how splitting the functionality to different packages when they rely on the same infrastructure could make things messy.  So maybe I think a Boolean option would be a good substitute for splitting out into a package. A good example of this user centricity is Hop's way of implementing functionality but letting users pick keybindings (even though I kind of wish that they had some preconfigured defaults). Ok that's all I have to say it's still a great plugin!

**Comment by ggandor** [comment]
Yeah I get what you're trying to say - my short answer is that I don't want to clutter/complicate the API with readily available settings for features that are not "natural" for this plugin, only to make the onboarding experience for some veteran users a tiny bit better. The same reason why I won't hard-wire the "native-like" `;`/`,` into the plugin.
I _do_ provide ways to achieve those behaviours though, because we should respect those users too, obviously. `umap f | unmap F | unmap t | unmap T` is a really simple line to be added to one's config.

Moreover, a `disable-ft` flag would be totally arbitrary. Why not `disable-s`, or even `disable-x`, or any other combinations then? Having a `do-not-set-any-default-mappings` flag would at least make some sense, even if I'm not really keen on that (and indeed I've kept [that issue](https://github.com/ggandor/lightspeed.nvim/issues/11) open). If there are no serious objections, I think I'm closing now, because this specific request seems more or less out of the question, and we can discuss things further at the aforementioned thread.
