### ISSUE TITLE
Issue with f/t's same-key repeat

### ISSUE THREAD

**Issue by jandamm** [ggandor/lightspeed.nvim#55]
Thanks for creating this plugin. I'm liking it so far but I encountered one issue where the native f/t was nicer (or I'm doing it wrong 😉)

Imagine this situation where `|` is the cursor.
```
 |   hello abcade
 ```
 When I would want to delete `abca`.
 
 With native `f` I would type `fad;`.
 
 With lightspeed I haven't found a way except `fadfa`. I would have expected `fadf<CR>` to work but this deleted until the end of line.

**Comment by ggandor** [comment]
Hi! I cannot reproduce this, it deletes `abca`, as it should 🤔

**Comment by jandamm** [comment]
Hmm, weird. Now it works for me as well 🤷‍♂️.
It might be because I had https://github.com/unblevable/quick-scope installed which also adds a map for `f`.

I now also added `omap ; f<CR>` and `omap , F<CR>` which lets me use `fad;` as well while still being able to remap `;`/`,` to something else 👍

**Comment by ggandor** [comment]
You could also check the workaround in `:h lightspeed-custom-ft-repeat-mappings` (doing only the `omap`s then), so that you can repeat `t/T` too.
