### ISSUE TITLE
Operator f/t does not set last search

### ISSUE THREAD

**Issue by jandamm** [ggandor/lightspeed.nvim#56]
When I do the following:

`fa` `dfb` `f<CR>` I will jump to the next `a` instead of `b`.

Is this intended behavior? I'd assume it'd jump to `b` instead of `a`.

**Comment by ggandor** [comment]
I'm a mind reader, just fixed this in the most recent commit a few hours ago (not pushed yet).

**Comment by jandamm** [comment]
Thanks, looks good :)
I also like the new mapping to use `;` to repeat the last search.
