### ISSUE TITLE
`conceallevel` not restored in operator-pending mode f/F/t/T

### ISSUE THREAD

**Issue by zeertzjq** [ggandor/lightspeed.nvim#61]
Steps to reproduce:
1. Open a `.tex` file with the following content:
```latex
\begin{document}
$\beta$
\end{document}
```
2. `:set conceallevel=2`
3. Press `ytt`
4. `conceallevel` becomes `0`

Operator-pending mode `z` and `Z` do restore `conceallevel`, but `f`/`F`/`t`/`T` don't.

**Comment by ggandor** [comment]
Yep, indeed... In operator-pending mode for `f/t` I forgot to use the `exit` form that triggers the `LightspeedLeave` User event (which in turn triggers restoring the editor options). Thanks very much for reporting!
