### ISSUE TITLE
Restore greyed out area after jump to 1st match after a timeout

### ISSUE THREAD

**Issue by mikehaertl** [ggandor/lightspeed.nvim#62]
First: thanks for this awesome plugin! I really start to get the hang of it.

But after some weeks of use I found one thing that could maybe be tweaked. It's about this feature (from the README):

> the cursor automatically jumps to the first match by default; pressing any other key than a group-switch or a target label exits the plugin now

After typing 2 chars I often find, that I'm already where I wanted to go. But now the area is still greyed out. All I wanted to do is go to that new location, e.g. to reason about some piece of code. But my brain feels disturbed a lot by the still greyed out area. I now feel a disruption because I have think about "How can I get rid of that greyed out area?". I could press a key without any binding (`ESC` is to far away. On my german keyboard `ä` may be a good candidate). But it still requires me to press yet another key - for no real action.

I wonder if we couldn't just get a (configurable) timeout: After the cursor jumped to the first match, we could wait `x` seconds and then exit the plugin and restore the greyed out area.

Does this make sense? Or is there an even better alternative that I'm missing?

**Comment by ggandor** [comment]
Implemented by cf38aa8421d2b6a7c993d0ca077ce2153a22e965. (Wrong reference in the commit message. To err is human.)

**Comment by mikehaertl** [comment]
Seems to work fine, thanks!
