### ISSUE TITLE
Dot-repeat just inserts 'plug'

### ISSUE THREAD

**Issue by d-miketa** [ggandor/lightspeed.nvim#63]
Pressing `.` after a lightspeed jump just inserts the word `plug` at my current position. The relevant bits in my Packer config are

```
use {
    'ggandor/lightspeed.nvim',
    requires = {
        'tpope/vim-repeat'
    },
}
```

**Comment by ggandor** [comment]
Could you give me a reproducible example with the contents of the buffer and the full key-sequence entered?

**Comment by ggandor** [comment]
I cannot reproduce the problem, and no one else has reported a similar issue in over a month now, so closing this.

**Comment by d-miketa** [comment]
Sorry, I forgot to follow up on this. I can’t currently reproduce it; may have been a random interaction or a bug that was fixed in a random patch. Thank you for the plug-in, still adapting to it but liking it very very much. :)
