### ISSUE TITLE
Discussion: x-mode (VOTE: should we deprecate the "prefix key" option?)

### ISSUE THREAD

**Issue by ggandor** [ggandor/lightspeed.nvim#65]
Now that we have `<Plug>` keys for x-mode, I don't really see the practical purpose of providing a "prefix" key option anymore, it's inelegant, and just complicates the code unnecessarily. In Normal mode, one rarely wants to jump to an exact position, we're targeting text objects most of the time. In Visual mode, one can map the `<Plug>` keys to `x/X` if really needed (and use `d/D` for delete), but even without that, pressing something like `<c-x>` is actually more cumbersome than just pressing `l` afterwise. (Ok, in the reverse direction it's worse.) OTOH, if one sets the prefix to some very comfortable key (`space` or something like that), it _might_ be useful... Opinions? Any objections to removing it?

EDIT: You can leave a "thumbs up" reaction if you're fine with the removal, and a "thumbs down" otherwise.

**Comment by ggandor** [comment]
Well, the committee seems more or less unanimous...

**Comment by ggandor** [comment]
> ...include the cursor position and my target character. This is what happens in visual mode, but if I want to yank or delete, the behavior becomes far too complicated and stops being intuitive.

Well, it's about being consistent with `/` and `?`, they behave the exact same way as Lightspeed `s`/`z` in all modes. You can say that's unintuitive, but this was a choice I had to make back then (Sneak does the same by the way). Much effort has been put into working consistently with native Vim motions, including the interplay with forcing modifiers (`v`, `V`, `ctrl-v`).

> So how do I get to the target character itself?

The `z` motion is **exclusive**, just like `/`. In operations, the target will not included in the operated area. You can force it being `inclusive` by `v` - that is, pressing `zv` and then the target, just like in case of `/?` (`:h forced-motion`). On the other hand, `x` is an **inclusive** motion in Op-pending mode. You can force it to `exclusive` also by the `v` toggle. In the end, `zv` and `xv` are equivalent.

> I either miss out on the last character, or I input »Enter« to get to the end and then one character of the next line is deleted too.

Yes, that can be considered a bug! But I haven't found a solution yet. In x-mode, if you target the last character on a line (`a\nb`), then you'll get a "split" match, extending to the first char of the following line (`ab`). The best solution would be to include a _newline_ character in the match (`a\n`), but that is far from trivial AFAIK.

**Comment by luetage** [comment]
I understand. It’s laudable that you keep everything compatible. I used to use sneak for about a year before I switched over to lightspeed, but I can tell you that I could never get used to this behavior (which is different forwards/backwards) and always selected in visual mode. I know how it works in theory, but it’s simply not second nature to me and therefore it’s just an annoyance when I really want to think about the code and not the range I’m influencing.

Should you at some point feel it’s worthwhile to introduce a “literal” mode in addition, I would welcome it. If not, it’s no big deal. I’ll just continue selecting visually instead before deleting/yanking/etc.

**Comment by luetage** [comment]
It took me too long to realize `vz` and `vZ` is indeed the solution to my preference. I’m aware this might be off‐topic now, but mapping the lightspeed_s shortcuts to m/M in operator‐pending mode and then mapping z/Z to vm/vM solved this issue for me. Please disregard the feature suggestion I posted above, it’s obviously not needed.

**Comment by ggandor** [comment]
Yeah, I should probably mention this trick somewhere in the docs. By the way, the clean solution is:
```
omap ? v<Plug>Lightspeed_s
```

**Comment by ggandor** [comment]
> It all becomes even more erratic when I want to delete or yank from the middle of one line until the end of another line.

Just noting that https://github.com/ggandor/lightspeed.nvim/commit/d4854f8e11483bf100e4e7495c6eea04c73e4653 presumably fixed the issues you mentioned, now `x` never yanks/deletes beyond the current line (at least if I didn't miss something - it's easy to get lost in all these combinations :D).
