### ISSUE TITLE
f,F,t,T do not work in macros

### ISSUE THREAD

**Issue by alexander-born** [ggandor/lightspeed.nvim#7]
Love the plugin, but f,F,t,T do not work in macros anymore.

**Comment by ggandor** [comment]
Thanks for the report! Yeah, I can reproduce such issues. I'm clueless at the moment, but will investigate this.

**Comment by sQVe** [comment]
This also applies to for the `normal` command. I have to run `:norm!` for `f@dW` to work.

**Comment by sQVe** [comment]
`vim-sneak` also has this problem but only when setting `let g:sneak#s_next = 1`.

**Comment by ggandor** [comment]
This reinforces my suspicion that this is about the "instant-repeat" feature, maybe `feedkeys()` causes problems...?

**Comment by ggandor** [comment]
This might be related: justinmk/vim-sneak#264

**Comment by sQVe** [comment]
@ggandor ☝🏼 issue is for sure related to that.

**Comment by rktjmp** [comment]
For others, my work around is this, which seems to work fine:

```viml
" divert lightspeed in macros because fFtT misbehave
nmap <expr> f reg_recording() .. reg_executing() == "" ? "<Plug>Lightspeed_f" : "f"
nmap <expr> F reg_recording() .. reg_executing() == "" ? "<Plug>Lightspeed_F" : "F"
nmap <expr> t reg_recording() .. reg_executing() == "" ? "<Plug>Lightspeed_t" : "t"
nmap <expr> T reg_recording() .. reg_executing() == "" ? "<Plug>Lightspeed_T" : "T"
````

For what it's worth, I've previously had issues with `feedkeys` in macros, my solution was replacing it with `<expr>` maps.

Not sure if that's appropriate/doable here, nor whether the issue was related incompatibilities around mixing feed keys and macros or if I was just misapplying feed keys.

**Comment by ggandor** [comment]
@rktjmp Perfect workaround, many thanks! I didn't know about the `reg_recording` and `reg_executing` functions. We should probably add this to the readme. 

It's a pity that we cannot do something similar for `norm` (as `norm!` disables all the other custom mappings, so that is not ideal).

**Comment by ggandor** [comment]
Eureka, it seems we have caught the problem, and there is a solution for this, the workaround is not even necessary! From `:h feedkeys()`:
```
By default the string is added to the end of the typeahead
buffer, thus if a mapping is still being executed the
characters come after them.  Use the 'i' flag to insert before
other characters, they will be executed next, before any
characters from a mapping.
```
With the `i` flag added to `feedkeys`, macros and `norm` work without issues! With `reg_recording` and `reg_executing` available, we can even limit the scope of f/t to the current line in those cases (that is probably the more intuitive behaviour - or we can make it optional, however we want).

**Comment by ggandor** [comment]
I have to think through how best to handle limiting the scope to the current line, we should probably open a new issue for that.

**Comment by alexander-born** [comment]
Great find! Works as expected now. 
I hope the `i` flag fixes a similar problem in nvim-compe. See https://github.com/hrsh7th/nvim-compe/issues/416
