### ISSUE TITLE
Let <Plug>Lightspeed_;_ft and <Plug>Lightspeed_,_ft work as motions that can accept an operator

### ISSUE THREAD

**Issue by jam1015** [ggandor/lightspeed.nvim#74]
I have 
```
"nmap ; <Plug>Lightspeed_;_ft
"nmap , <Plug>Lightspeed_,_ft
```

in my setup.   It would be nice to be able to type `d;` or `c;` to delete or change to the next occurrence of the last searched character.

I know you think deeply about this plugin and have engineered it in a very opinionated way.  Just thought that this was a small piece of functionality that couldn't hurt to include.

**Comment by ggandor** [comment]
You just forgot the `omap`s, of course it won't work with Normal mode mappings 😉 (I'm not _this_ opinionated 😀)

**Comment by jam1015** [comment]
good catch
