### ISSUE TITLE
Unable to get labels working when using Neovim for VSCode

### ISSUE THREAD

**Issue by dennyi** [ggandor/lightspeed.nvim#76]
When using lightspeed in VSCode with the Neovim extension, when using 2 char search, labels are not displayed, only the targets are highlighted. When using nvim directly, this works fine.

Example: when using command sbl , the following happens:
![image](https://user-images.githubusercontent.com/5374366/141264679-d94c9c9e-65a2-4e54-b0b0-f79428dc3d68.png)

**Comment by ggandor** [comment]
This is something that should be fixed by `vscode-neovim` (and/or core) eventually. Related issues:
https://github.com/asvetliakov/vscode-neovim/issues/363
https://github.com/justinmk/vim-sneak/pull/284
https://github.com/justinmk/vim-sneak/pull/285

**Comment by theol0403** [comment]
This will soon be fixed by https://github.com/vscode-neovim/vscode-neovim/pull/868!

**Comment by theol0403** [comment]
Extmark/lightspeed is now supported in vscode! 

Important: currently, you need to set `hi LightspeedCursor gui=reverse` in your nvim config to make lightspeed work.
