### ISSUE TITLE
Using s/S closes folds when `foldlevel=0` is set in modeline

### ISSUE THREAD

**Issue by wimstefan** [ggandor/lightspeed.nvim#81]
Well the title says it all. Searching for a string with `s` or `S` highlights the first letter and closes all folds as soon as the second letter is hit while jumping to the first result. 
This only occurs when `foldlevel=0` is set in the modeline. When I remove that and set the option in my init.lua it does not happen anymore ...

Seems obscure and I hope you have already enough information to reproduce the issue. Please let me know if you need more information!

**Comment by ggandor** [comment]
Lol, I can reproduce. It's mysterious indeed, beyond my Vim knowledge 😊 My educated guess is that _something_ triggers reading the modeline when jumping (well, there's no other explanation), but beyond that, I'm in the dark.

**Comment by ggandor** [comment]
I fixed this, but I'm still super-curious about the reason. In case anyone wanders here with an explanation, please share it.

**Comment by wimstefan** [comment]
Wow that was a fast fix! Thanks a lot 🙏
