### ISSUE TITLE
Discussion: new labeling system

### ISSUE THREAD

**Issue by jandamm** [ggandor/lightspeed.nvim#82]
I've typed `sm`.

<img width="690" alt="Screenshot 2021-11-17 at 23 12 57@2x" src="https://user-images.githubusercontent.com/5963139/142291018-63c97199-21b2-4dc3-9d04-b1662521d609.png">
In previous versions the `o` in mnemonic would have been shifted over the `m` and highlighted differently.
It changed so that the `o` isn't shifted anymore but I find it confusing that it isn't highlighted anymore.

**Comment by ggandor** [comment]
Yep, https://github.com/ggandor/lightspeed.nvim/commit/117c0e8800eee90d3bdc91a486f3a6c3d645eafe. (The idea came from a [redditer](https://old.reddit.com/r/neovim/comments/qsbksd/lightspeednvim_takes_the_synergy_between_sneak/hkio6cw/).)

An indisputable advantage is that we've finally managed to reduce the overall visual noise a bit. And now the "shifted" beacons are even more distinguishable, because of the different highlight of the masked char.
Don't you think it's just a matter of getting used to it?

We could highlight the match itself, but simply giving them the white `LightspeedUnlabeledMatch` highlight would be very confusing. Introducing another highlight group just for this would add unnecessary noise I think... I might try that though.

**Comment by jandamm** [comment]
I found that commit as well but expected the previous highlighting but just moved one char to the right.

**Comment by ggandor** [comment]
Wouldn't that be even more confusing? Now if you see a brown masked char, you immediately know that that beacon is shifted/squeezed, and the end of the match is where the label is.

**Comment by jandamm** [comment]
For me it communicated "second char" 😅

**Comment by ggandor** [comment]
Well, I've been planning to experiment with these variations a little more anyway, although I think "no highlight" is pretty fine now.

**Comment by rktjmp** [comment]
I have nothing helpful to add other than that I have tried to get used to the new labeling style and still much prefer the old one. Additional to #86, it feels awkward when the label pushes outside of a word into whitespace.

![image](https://user-images.githubusercontent.com/866010/144357060-8cae4179-0255-45db-b4c9-7b3631afcae8.png)

**Comment by jandamm** [comment]
I still prefer the old highlighting scheme as well.

**Comment by ggandor** [comment]
Yeah, I think we might need a config option after all, I agree with both sides.

**Comment by ggandor** [comment]
IF there would be a flag, what would be a good name for it that is expressive but not overly verbose?

`show_labels_next_to_matches = true`

Verbose, and somewhat clumsy:

`show_labels_next_to_matches_if_possible = true`

The second one is pretty good, but "beacon" is such an obscure term, less intuitively
understandable than "label", without reading the README (or the codebase) thoroughly:

`always_sqeeze_beacons_into_match_width = false`

`force_beacons_into_match_width = false`

**Comment by rktjmp** [comment]
`labels_max_width = 2|(3?)|auto`? (`labels_maximum_width` might be more in-style.) `labels_width = 2|3|auto`? From the outside, I understand what the beacon is but it's also just "part of the label" to me conceptually, it's "part of what I type" so I am _not sure_ if having the term is useful/important.

`...match_width` is maybe an obtuse term IMO. I get what it means but I don't really think of light speed matches having a width, more of a point. (`collapse_labels_beacons_singularity`? :smile: )

`compress_labels`, `compress_match_labels` is maybe a bit vague.

`force_beacons_into_label`? `force_beacons_inside_labels`, `place_beacons_on_labels`? ~~`constrain_beacons_to_labels`?~~ Seems pretty explicit and by having `label` and `beacon` in the option you maybe infer that they are different things which *might* aid understanding of the option?

 `place_beacons_on_labels` says that
- the two terms are separate concepts, and 
- that beacon will be placed on top of (aka inside) the label and
- that the beacon will take rendering precedence over the label and
- doesn't include "show", so clear it doesnt effect the visibility of a beacon (as in show vs hide), pretty explicit?
 
`place_beacons_inside_labels` probably removes any ambiguity in my mind.

`move_beacons_inside_labels` (unclear, are we moving beacons that are inside to be out, or moving beacons to be inside from out?)
`shift_beacons_inside_labels` (unclear, are shifting out or in?)

**Comment by jandamm** [comment]
I second `labels_maximum_width = 2|3` or `labels_width = 2|auto`.

A maximum value of `auto` doesn't make sense to me.
A `label_width` of 3 would suggest it's always three.

Since it boils down to two values maybe a bool would make more sense. What would a user config of `labels_width` of 4 mean?

**Comment by ggandor** [comment]
Just to be on the same page: I use the term **beacon** for any highlighting a match can get (the white unlabeled kind, when we just highlight the match itself, is considered a "beacon" too). 

A (non-overlapped) beacon can either be `[ch1][ch2]`, or `[char2][label]` (if "squeezed", as in the old system), or `..[label]` (as of now, in most cases). 

A **label** is thus a(n optional) _component_ of a beacon, the "wormhole" character itself that gets you to the match.

P.S.: I think this illustrates my point, i.e., so much for "beacon" & "label" being intuitive terms :)

**Comment by jandamm** [comment]
What about `always_squeeze_beacons` where the new (and default) would be `false`?

**Comment by rktjmp** [comment]
> I'm totally game for adding an undocumented g:collapse_lightspeed_beacons_into_singularity var as an easter egg. smile

I actually did wonder if that was the best option.

It can sit there with a bad name until you think of a nicer one, or maybe even a new labeling method comes to you which warrants an actual option.

It does feel a bit gross as a developer to have those "legacy" style options though, better for sanity to have it as a feature or not a feature. (Please no viml `g:` var though :vomiting_face:)

`wormhole_position = 1|2|3`? where it's placed in the first (new behaviour), second (legacy behaviour) or (extended to) third char (current behaviour) in a match? `wormhole_position_in_match`?

I guess really we are talking about almost a match "id"? Not sure if that would be a helpful term.

![image](https://user-images.githubusercontent.com/866010/145701503-5015d911-5163-4a63-9f0a-c827c3ee8040.png)

**Comment by ggandor** [comment]
`id` would make some sense if it would mirror the actual logic of the codebase, e.g. matches would be keyed by these chars in the data structure they sit in, but it's not the case. The "label" is more of a dynamically calculated attribute, e.g. it depends on whether we're auto-jumping or not.

**Comment by ggandor** [comment]
Okay, here it is. After all, `opts` fields are rather painless to change/deprecate, since we can programmatically message the user about them. Interestingly, I also find the old method better now... maybe we should set it as the default? :)

**Comment by rktjmp** [comment]
:tada:
