### ISSUE TITLE
Configuration to revert modified labeling system

### ISSUE THREAD

**Issue by rktjmp** [ggandor/lightspeed.nvim#86]
Is there a way to use the ~~objectively better~~ traditional labeling system that Lightspeed used to have?

Now when I have an 3rd letter to press I have to look _past_ the point I am matching, vs my eyes already seeing the 3rd key.

Previously:

![image](https://user-images.githubusercontent.com/866010/142967024-00ef1e61-b65e-40db-a0f0-f372c638a787.png)

Now

![image](https://user-images.githubusercontent.com/866010/142967092-afa9e9c8-d44e-4ca5-9873-6b86ff12721c.png)

**Comment by rktjmp** [comment]
Let me reposition this,

Is the maintenance burden of adding a configuration option high enough that it's not worth it and I should learn to live with the change or is this reasonable? You can say no.

**Comment by ggandor** [comment]
No, you have a point. In fact, both systems have pros and cons, so this might be a valid candidate for a config flag - in fact, I have already been considering adding it, along same lines of thought. But of course one always tries to avoid introducing such binary choices first, it would be better to reach some kind of consensus or optimal solution instead, _if_ possible. Let's continue the discussion here: https://github.com/ggandor/lightspeed.nvim/issues/82
