### ISSUE TITLE
; and ,  or . repeat not working for s/f/t. 

### ISSUE THREAD

**Issue by beauwilliams** [ggandor/lightspeed.nvim#91]
Hi, since the breaking changes I have tried to refactor to help doc.

I can not get it working. Am I doing something wrong?

My mappings.
```
vim.api.nvim_set_keymap('n', ';', '<Plug>Lightspeed_;_ft', { noremap = true, silent = true })
vim.api.nvim_set_keymap('x', ';', '<Plug>Lightspeed_;_sx', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', ',', '<Plug>Lightspeed_,_ft', { noremap = true, silent = true })
vim.api.nvim_set_keymap('x', ',', '<Plug>Lightspeed_,_sx', { noremap = true, silent = true })
```

Previously I had a function that worked perfectly.  Perhaps this can be refactored with minimal changes?

```
-- F(ROM) and T(O) MAPPINGS
---@diagnostic disable-next-line: lowercase-global
function repeat_ft(reverse)
	local ls = require('lightspeed')
	ls.ft['instant-repeat?'] = true
	ls.ft:to(reverse, ls.ft['prev-t-like?'])
end
vim.api.nvim_set_keymap('n', ';', '<cmd>lua repeat_ft(false)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('x', ';', '<cmd>lua repeat_ft(false)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', ',', '<cmd>lua repeat_ft(true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('x', ',', '<cmd>lua repeat_ft(true)<cr>', { noremap = true, silent = true })
```

**Comment by beauwilliams** [comment]
I've tried this too. I'm at a loss here. I would be happy to ditch ;/, for . but I can not seem to get it working still

```
					labels = nil,
					cycle_group_fwd_key = '.',
					cycle_group_bwd_key = '>',
					-- f/t
					instant_repeat_fwd_key = '.',
					instant_repeat_bwd_key = '>',
```

**Comment by beauwilliams** [comment]
I will revert to this 72ae01d2da40877e54e9977520b0f1380bef23cf commit now as I can't get repeat functionality working.

**Comment by ggandor** [comment]
```lua
require'lightspeed'.setup {
  instant_repeat_fwd_key = ';',
  instant_repeat_bwd_key = ','
}
```
should work fine, just like
```
vim.api.nvim_set_keymap('x', ';', '<Plug>Lightspeed_;_sx', { noremap = true, silent = true })
```
etc. Mysterious...

> Previously I had a function that worked perfectly. (...)

No, that is unnecessary, e.g. `<Plug>Lightspeed_;_sx` is just:
```
sx:go(require'lightspeed'.sx.state.cold['reverse?'], require'lightspeed'.sx.state.cold['x-mode?'], 'cold')
```
i.e., the same logic is encapsulated in them (with the API changes reflected).

Could you share your whole lightspeed setup? Maybe the problem is somewhere else.

**Comment by ggandor** [comment]
> I would be happy to ditch ;/, for .

Off-topic question: then - that is, if muscle memory is not the issue here - what's the problem with using `f/t` for repeat (the default)?

**Comment by ggandor** [comment]
Oh, I get it. Do not use `noremap` in the mappings, `<Plug>` keys are aliases for right hand sides, and as such, need to be used recursively.

Still, `instant_repeat_fwd_key = ';'` _should_ work as it is... does it?

(Also, just to be sure that we're on the same page, `cycle_group_fwd_key` is the key that shifts to the "blue" group, and is not the same as `<Plug>Lightspeed_;_sx`.)

**Comment by gegoune** [comment]
Seems like 
```lua
  instant_repeat_fwd_key = ';',
  instant_repeat_bwd_key = ',',
```
are only valid shortly after `ft/FT`. Once highlighting disappears they stop working.

For me having those keys working helps with switching to (n)vim in other places (servers) and being able to use muscle memory.

**Comment by ggandor** [comment]
@gegoune You can use `<Plug>Lightspeed_;_ft` then. (And the timeout for instant-repeat can be configured by setting `opts.exit_after_idle_msecs.unlabeled = ...`.)

**Comment by beauwilliams** [comment]
> ```lua
> require'lightspeed'.setup {
>   instant_repeat_fwd_key = ';',
>   instant_repeat_bwd_key = ','
> }
> ```
> 
> should work fine, just like
> 
> ```
> vim.api.nvim_set_keymap('x', ';', '<Plug>Lightspeed_;_sx', { noremap = true, silent = true })
> ```
> 
> etc. Mysterious...
> 
> EDIT: `noremap` should _not_ be set to `true`, this must have been the source of the problem (for this latter at least).
> 
> > Previously I had a function that worked perfectly. (...)
> 
> No, that is unnecessary, e.g. `<Plug>Lightspeed_;_sx` is just:
> 
> ```
> sx:go(require'lightspeed'.sx.state.cold['reverse?'], require'lightspeed'.sx.state.cold['x-mode?'], 'cold')
> ```
> 
> i.e., the same logic is encapsulated in them (with the API changes reflected).
> 
> Could you share your whole lightspeed setup? Maybe the problem is somewhere else. (And update to the most recent commit first.)

Aha, yes it was the noremap. Thanks!

Small little detail but was easy to miss during refactor. Hopefully if anyone else has this issue now they can see here how to solve it.

**Comment by beauwilliams** [comment]
> > I would be happy to ditch ;/, for .
> 
> Off-topic question: then - that is, if muscle memory is not the issue here - what's the problem with using `f/t` for repeat (the default)?

Interesting. I don't mind it at all! I swear I tried it earlier and it was not working for me but it is now :)

I think its a pretty reasonable default
