### ISSUE TITLE
x-mode configable feature request.

### ISSUE THREAD

**Issue by singlexyz** [ggandor/lightspeed.nvim#97]
When I was using x-mode, I encountered a situation that was different from what I expected. 

First of all, here's my keymappings :
```lua
vim.api.nvim_set_keymap('o', ']', '<Plug>Lightspeed_x', { noremap = false })
vim.api.nvim_set_keymap('o', '[', '<Plug>Lightspeed_X', { noremap = false })
```

I have the following text and I want to turn it into `medium hard`.
(m) means cursor on it.
```
simple (m)edium hard
```
So I press `c[s`, it becomes 
```
simedium hard
```

https://github.com/ggandor/lightspeed.nvim#x-mode
I checkout the document and found that it works like that.

Now `Lightspeed_x` works like `f`, `Lightspeed_X` works like `T`.
This may be different from the habits of many people.
I prefer `Lightspeed_x` works like `t`, `Lightspeed_X` works like `F`.

So is it possible to make this function configurable, or directly expose four interfaces, like:
`Lightspeed_xf`, `Lightspeed_xt`, `Lightspeed_XF`, `Lightspeed_XT`

**Comment by ggandor** [comment]
> I prefer Lightspeed_x works like t, Lightspeed_X works like F.

This is exactly how `Lightspeed_s` & `Lightspeed_S` works (`z/Z` in op-mode according to the default keymaps), why don't you map those to `]/[` then?

**Comment by singlexyz** [comment]
> This is exactly how `Lightspeed_s` & `Lightspeed_S` works (`z/Z` in op-mode according to the default keymaps), `dZs` would leave `medium hard` on the screen. Why don't you map those to `]/[` then?

Ah yes, this is exactly what I want. 
I just checked the document, `Lightspeed_z/Z` are not defined like `Lightspeed_x/X`, only use the default key(z/Z).

**Comment by ggandor** [comment]
> I just checked the document, Lightspeed_z/Z are not defined like Lightspeed_x/X, only use the default key(z/Z).

Yeah, of course, we are looking for certain behaviours, a `<plug>` key, e.g. `Lightspeed_s` is just an alias for a function call with specific arguments, corresponding to one of the behaviours (`Lightspeed_s` = `lightspeed.sx:go(false, nil, nil)` = forward, not-x-mode, not-repeat). It's arbitrary that we named the `<plug>` keys `_s`/`_S` (after the default Normal and Visual keymaps), and that by default we map `z/Z` to them in operator-pending mode, to avoid conflict with surround plugins.
So all you have to do is changing `Lightspeed_x/X` to `Lightspeed_s/S` in your mappings.

**Comment by singlexyz** [comment]
> 

Aha, great. Thank you very much for your work and design this awesome plugin.
