### ISSUE TITLE
difficulty with fwd and backword cycle group mappings

### ISSUE THREAD

**Issue by ldelossa** [ggandor/lightspeed.nvim#99]
Hello, 

I'm trying to use tab, s-tab to cycle match groups. The issue is every time I hit tab neovim produces an actual white space movement and ends the search all together.

Is this something with my neovim configuration?

**Comment by ggandor** [comment]
I cannot reproduce this,
```
require'lightspeed'.setup { cycle_group_fwd_key = '<tab>', cycle_group_bwd_key = '<s-tab>' }
```
should work...

> Is this something with my neovim configuration?

That shouldn't be a problem, the shift/cycle keys are just `getchar`-d inside the function, separated from the outside world...

**Comment by ldelossa** [comment]
Unless I am not using this correctly, I hit "s" then "l" since I'm searching for the word "lua". The lines I'm interested are highlighted in blue, so I hit "tab". Once I hit tab tho, it ends my search. 


https://user-images.githubusercontent.com/5642902/144469645-fd12c2ec-e053-4c06-af91-70fc08a821d9.mp4

**Comment by ggandor** [comment]
I see! You should finish the 2-char pattern first (`lu`), and only then can you use the group-shift keys.

**Comment by ldelossa** [comment]
there we go! thanks a lot.
